"""FROZEN pre-unification snapshots (DO NOT EDIT — golden-test reference data).

Byte-exact copies (AST-extracted, values verbatim) of the four LIVE scrapers' private TYPE/CITY
maps as they existed at origin/main commit 1c977a3, immediately BEFORE fix/normalize-unification
routed them through scrapers/common/normalize.py. test_normalize_unification_golden.py replays
the OLD lookup logic over these snapshots and asserts the NEW unified path produces byte-identical
output for every previously-mapped input. If a scraper's mapping is deliberately changed later,
regenerate/adjust the golden test alongside it — never edit these dicts to make a test pass.

Underscore-prefixed module name keeps pytest from collecting it as a test file.
"""

OLD_WASALT_TYPE_MAP = {
    'Apartment': 'Apartment',
    'Villa': 'Villa',
    'Townhouse': 'Villa',
    'Duplex': 'Villa',
    'Floor': 'Floor',
    'Building': 'Building',
    'Residential Building': 'Building',
    'Land': 'Residential Land',
    'Residential Land': 'Residential Land',
    'Plot': 'Residential Land',
    'Rest House': 'Rest House',
    'Resthouse': 'Rest House',
    'Chalet': 'Chalet',
    'Farm': 'Farm',
    'Room': 'Room',
    'Small apartment (studio)': 'Apartment',
    'Studio': 'Apartment',
    'Office': 'Office',
    'Office Space': 'Office',
    'Shop': 'Shop',
    'Commercial Shop': 'Shop',
    'Warehouse': 'Warehouse',
    'Showroom': 'Showroom',
    'Commercial Land': 'Commercial Land',
    'Commercial Building': 'Commercial Building',
    'Tower': 'Commercial Building',
    'Hotel': 'Hotel',
    'Workshop': 'Workshop',
    'Repair shop': 'Workshop',
    'Gas Station': 'Gas Station',
    'Station': 'Gas Station',
    'Kiosk': 'Kiosk',
    'Booth': 'Kiosk',
    'Parking': 'Parking',
    'Car parking': 'Parking',
}

OLD_WASALT_CITY_MAP = {
    'Riyadh': 'Riyadh',
    'Jeddah': 'Jeddah',
    'Khobar': 'Khobar',
    'Al Khobar': 'Khobar',
    'Makkah Al Mukarramah': 'Mecca',
    'Makkah': 'Mecca',
    'Mecca': 'Mecca',
    'Aldammam': 'Dammam',
    'Al Dammam': 'Dammam',
    'Dammam': 'Dammam',
    'Madinah': 'Medina',
    'Al Madinah Al Munawwarah': 'Medina',
    'Medina': 'Medina',
    'Alttayif': 'Taif',
    'Al Taif': 'Taif',
    'Taif': 'Taif',
    'Al Ahsa': 'Hofuf',
    'Al Hofuf': 'Hofuf',
    'Hofuf': 'Hofuf',
    'Alzahran': 'Dhahran',
    'Dhahran': 'Dhahran',
    'Khamis Mushayt': 'Khamis Mushait',
    'Khamis Mushait': 'Khamis Mushait',
    'Eanizah': 'Unaizah',
    'Unaizah': 'Unaizah',
    'Bariduh': 'Buraidah',
    'Buraidah': 'Buraidah',
    'Almuzahimih': 'Al Muzahimiyah',
    'Thawl': 'Thuwal',
    'Jubail Industrial City': 'Jubail',
    'Jubail': 'Jubail',
    'Al Jubail': 'Jubail',
    'Alqunafdhuh': 'Al Qunfudhah',
    'Al Qatif': 'Qatif',
    'Qatif': 'Qatif',
    'Jazan': 'Jazan',
    'Abha': 'Abha',
    'Abqaiq': 'Abqaiq',
    'Diriyah': 'Diriyah',
    'Al Kharj': 'Al Kharj',
    'Al Baha': 'Al Baha',
    'Al-Namas': 'Al Namas',
    'Najran': 'Najran',
    'Tabuk': 'Tabuk',
    'Hail': 'Hail',
    'Arar': 'Arar',
    'Sakaka': 'Sakaka',
    'Yanbu': 'Yanbu',
    'Hayil': 'Hail',
    'Hafar Al-Batin': 'Hafar Al Batin',
    'Al Hayathem': 'Al Hayathim',
    'Al Jumum - Bahra': 'Al Jumum',
    'Aljumum': 'Al Jumum',
    'Ahad Rafidah': 'Ahad Rafidah',
    'Ahad Rifaydah - Al-Wadyin Station': 'Ahad Rafidah',
    'Ahad Almasarihah': 'Ahad Al Masarihah',
    'Samith': 'Samtah',
    'Samtah - Alqafl': 'Samtah',
    'Tbwk': 'Tabuk',
    "Abu Arish - 'Abu Earish": 'Abu Arish',
    "Sibya'": 'Sabya',
    'Ar Rass': 'Ar Rass',
    'Al Jubaylah': 'Jubail',
    'Alliyth': 'Al Lith',
    'Bisha': 'Bisha',
    "Al-Majma'Ah": 'Al Majmaah',
    'Malahum': 'Mahayel',
    'Muhayil': 'Mahayel',
    'Almudhanib': 'Al Mithnab',
    'King Abdullah Economic City': 'KAEC',
    "Biqaea'": 'Baqaa',
    'Albadayie': 'Al Badai',
    "Al-Quway'Iyah": 'Al Quwayiyah',
    'Al Quwayiyah - Al Ruwaydah': 'Al Quwayiyah',
    'Earear': 'Arar',
    'Eafif': 'Afif',
    'Al Aflaj': 'As Sulayyil',
    'Wadi Ad-Dawasir': 'As Sulayyil',
    'Rabigh': 'Rabigh',
    'Riyadh Al Khabra': 'Riyadh Al Khabra',
    'Al Khafji': 'Khafji',
    'Dawadmi': 'Dawadmi',
    'Alghat': 'Al Ghat',
    'Qurayyat': 'Qurayyat',
    'Sharurah': 'Sharurah',
    'Sakakah': 'Sakaka',
    'Baysh': 'Baysh',
    'Thadiq': 'Thadiq',
    'Shaqra': 'Shaqra',
    'Baljurashi': 'Al Baha',
    'Al-Makhwah': 'Al Baha',
    'Al-Aqiq': 'Al Baha',
    'Darih': 'Al Baha',
    'Nariya': 'An Nairyah',
    'Aleuyun': 'Al Uyun',
    'Alnabhaniyah': 'An Nabhaniyah',
    'Almajardah': 'Al Majardah',
    'Al Ghazalah - Al Ghazalah': 'Al Ghazalah',
    'Al Ghazalah - Alruwduh': 'Al Ghazalah',
    'Ash Shinan': 'Ash Shanan',
    'Rawdat Sudair': 'Al Majmaah',
    'Ashayrah Sudair': 'Al Majmaah',
    'Thuqbah': 'Khobar',
    'Al Qaisumah': 'Hafar Al Batin',
    'Mahd Al Thahab': 'Mahd adh Dhahab',
    'Sarat Ubaida': 'Khamis Mushait',
    "Harimla'": 'Thadiq',
    'Ramah': 'Rumah',
    'Darma': 'Diriyah',
}

OLD_ALDARIM_TYPE_MAP = {
    'land': 'Residential Land',
    'villa': 'Villa',
    'townhouse': 'Villa',
    'duplex': 'Villa',
    'mansion': 'Villa',
    'apartment': 'Apartment',
    'tower_apartment': 'Apartment',
    'building_apartment': 'Apartment',
    'villa_apartment': 'Apartment',
    'floor': 'Floor',
    'villa_floor': 'Floor',
    'building': 'Building',
    'farm': 'Farm',
    'istraha': 'Rest House',
    'compound': 'Compound',
    'office': 'Office',
    'store': 'Shop',
    'storage': 'Warehouse',
    'showroom': 'Showroom',
    'resort': 'Hotel',
    'hotel': 'Hotel',
}

OLD_ALDARIM_CITY_MAP = {
    'Makkah Al Mukarramah': 'Mecca',
    'Makkah': 'Mecca',
    'Al Madinah Al Munawwarah': 'Medina',
    'Al Madinah': 'Medina',
    "Ad Dir'iyah": 'Diriyah',
    'Ad Diriyah': 'Diriyah',
    "Al 'ammariyah": 'Al Ammariyah',
    'Al Khobar': 'Khobar',
    'Aldammam': 'Dammam',
}

OLD_EASTABHA_TYPE_MAP_AR = {
    'شقة': 'Apartment',
    'شقه': 'Apartment',
    'شقق سكنية': 'Apartment',
    'شقق': 'Apartment',
    'استوديو': 'Studio',
    'ستوديو': 'Studio',
    'دوبلكس': 'Duplex',
    'دوبليكس': 'Duplex',
    'فيلا': 'Villa',
    'فلة': 'Villa',
    'قصر': 'Villa',
    'بيت': 'House',
    'منزل': 'House',
    'دور': 'Floor',
    'دور سكني': 'Floor',
    'دور أرضي': 'Floor',
    'روف': 'Floor',
    'روف للبيع': 'Floor',
    'عمارة': 'Building',
    'عمارة عضم': 'Building',
    'عماره': 'Building',
    'أرض': 'Land',
    'ارض': 'Land',
    'أرض سكنية': 'Land',
    'ارض سكنية': 'Land',
    'أرض زراعية': 'Land',
    'ارض زراعية': 'Land',
    'أرض تجارية': 'Commercial Land',
    'مزرعة': 'Farm',
    'استراحة': 'Rest House',
    'إستراحة': 'Rest House',
    'شاليه': 'Chalet',
    'محل': 'Shop',
    'محلات تجارية': 'Shop',
    'محلات': 'Shop',
    'معرض': 'Showroom',
    'مكتب': 'Office',
    'مستودع': 'Warehouse',
    'صناعي': 'Warehouse',
    'محطة بنزين': 'Gas Station',
    'كافيه': 'Shop',
    'كافيه - لاونج': 'Shop',
    'تجاري': 'Commercial Land',
}

OLD_EASTABHA_CITY_MAP_AR = {
    'أبها': 'Abha',
    'ابها': 'Abha',
    'احد رفيده الوادين': 'Ahad Rafidah',
    'أحد رفيدة': 'Ahad Rafidah',
    'خميس مشيط': 'Khamis Mushait',
    'النماص': 'Al Namas',
    'تنومة': 'Tanomah',
    'بيشة': 'Bisha',
    'تثليث': 'Tathleeth',
    'محايل': 'Muhayil',
    'ظهران الجنوب': 'Dhahran Al Janub',
    'سراة عبيدة': 'Sarat Abidah',
    'الرياض': 'Riyadh',
    'الخرج': 'Al Kharj',
    'الدوادمي': 'Dawadmi',
    'المجمعة': 'Majmaah',
    'الزلفي': 'Zulfi',
    'القويعية': 'Quwaiiyah',
    'الدرعية': 'Diriyah',
    'جدة': 'Jeddah',
    'مكة المكرمة': 'Mecca',
    'مكة': 'Mecca',
    'الطائف': 'Taif',
    'الجموم': 'Al Jumum',
    'تربة': 'Turbah',
    'المدينة المنورة': 'Medina',
    'العلا': 'Al Ula',
    'الدمام': 'Dammam',
    'الخبر': 'Khobar',
    'الظهران': 'Dhahran',
    'القطيف': 'Qatif',
    'الجبيل': 'Jubail',
    'الأحساء': 'Hofuf',
    'الاحساء': 'Hofuf',
    'الخفجي': 'Khafji',
    'بقيق': 'Buqayq',
    'بريدة': 'Buraidah',
    'الرس': 'Ar Rass',
    'البكيرية': 'Bukayriyah',
    'المذنب': 'Muthnib',
    'تبوك': 'Tabuk',
    'تيماء': 'Tayma',
    'حائل': 'Hail',
    'نجران': 'Najran',
    'جازان': 'Jazan',
    'بيش': 'Bish',
    'الباحة': 'Al Baha',
    'بلجرشي': 'Baljurashi',
    'العقيق': 'Al Aqiq',
    'القريات': 'Qurayyat',
    'البرك': 'Al Birk',
}

OLD_MUSTQR_TYPE_MAP = {
    'فيلا': 'Villa',
    'شقة': 'Apartment',
    'دور': 'Floor',
    'دوبلكس': 'Villa',
    'بيت': 'House',
    'حوش': 'House',
    'عمارة': 'Building',
    'استراحة': 'Rest House',
    'شاليه': 'Chalet',
    'أرض': 'Residential Land',
    'ارض زراعية': 'Farm',
    'صالة': 'Showroom',
    'فندق': 'Hotel',
    'مكتب': 'Office',
    'محطة': 'Gas Station',
}

OLD_EASTABHA_DEAL_WORDS = ('للبيع', 'للايجار', 'للإيجار', 'إيجار', 'ايجار', 'بيع', 'مزاد', 'سكنية', 'سكني', 'أرضي', 'ارضي')
