-- MIRROR of the production object. NOT a migration — see the full-body-replace rule.
--
-- Re-verified 2026-09-03 (district_options_ar table-scope fix, migration 20260903224522). The
--   pending re-verification the 2026-09-02 note below DEMANDED is now DONE: md5(pg_get_functiondef)
--   read live from production under the deploy lock = 178deacbfa50de38e6b5a18e09bc737b, byte-identical
--   to the md5 recorded in this file. So 20260902220100 did apply, the p_has_license arm live in
--   production is the fixed one, and this mirror is confirmed against the real object rather than
--   against a rolled-back dry run. Nothing in the body was edited.
--   Re-stamped because 20260903224522 NAMES this object: it rebuilds district_options_ar around
--   af_eligibility_clause() so the district panel stops carrying its own second opinion about
--   eligibility. The clause itself is unchanged — the new caller is what changed.
-- Refreshed 2026-09-02 (AF matrix certification, BUG-1 fix): the p_has_license arm is now
--   `(p_has_license is null or (p_has_license and s.license_number is not null))` — false admits only an
--   explicit unlicensed fact, and canonical data carries none, so it admits nothing (silent → NULL, never
--   unknown → NO). Text + md5 captured from a rolled-back dry run of that migration against production
--   (a fresh Supabase branch could not be used: branch migrations fail at 20260621194329, pre-existing
--   drift). md5(pg_get_functiondef) of the would-be object = 178deacbfa50de38e6b5a18e09bc737b.
--   SHIP MUST RE-VERIFY this md5 against the live object after applying 20260902220100 under the deploy
--   lock; until then the live object still reads 681da577d8e10df55e30c345d284e139 (pre-fix).
--
-- Refreshed 2026-08-28 (first capture) by the AF + Trending Data Integrity routine (docs/ops/AF_TRENDING_DATA_INTEGRITY_ENGINEER.md).
-- Re-verified 2026-09-02 during the AF option-truth certification: md5(pg_get_functiondef) read
--   live from production = 681da577d8e10df55e30c345d284e139, identical to the md5 recorded below,
--   so the clause is UNCHANGED. Re-stamped only because that certification's migrations name this
--   object (the staleness rule matches any MENTION, deliberately, since a needle-edit can change a
--   body without a literal CREATE OR REPLACE — see 20260805190111/aqar_parse). Nothing was edited.
--   af_eligibility_clause() is THE canonical Advanced Filter predicate: every AF count surface and
--   the results RPC are generated by concatenating it (rebuild_af_filter_rpcs()), which is exactly
--   why AGENTS.md forbids hand-editing the four AF RPCs. It had NO mirror, so the one predicate a
--   session most needs to read was invisible in the repo — recoverable only by querying production,
--   which an offline barrier and a CI job cannot do. That is how the oracle-vocabulary drift fixed
--   in this same change survived: nothing in the tree stated what tokens the clause accepts.
--   Re-derived verbatim from pg_get_functiondef (base64 round-trip), never hand-transcribed.
--   Original capture was byte-exact at 8,574 octets (length() reported 8,501 characters — the
--   difference is multi-byte Arabic literals). Confirmed unchanged (same content) on 2026-08-29 and
--   2026-08-30, each time because a migration READ this clause (to derive monitored columns, and to
--   swap the __AF_ELIGIBILITY_WHERE__ placeholder back in after a template repair) without
--   redefining it — the staleness barrier cannot tell "mentions" from "replaces", so both dates were
--   honest re-verifications against production, never re-dates without a check.
-- Re-verified 2026-08-31 — CHANGED (this time a real redefinition, not a mention).
--   20260831205347_af_amenity_tokens_residential_rich_set.sql needle-edited the amenity whitelist +
--   predicate block to add gym, pool, garden, balcony, laundry_room, optical_fibers,
--   separate_electricity_meter and separate_water_meter (owner ruling, gym-bug-class sweep — see
--   that migration's own header for the full rationale and live counts).
--   Re-derived via a PostgREST RPC call to the live function this time, not pg_get_functiondef —
--   same non-hand-transcribed principle: the executed VALUE was fetched byte-exact over HTTP, then
--   the E'' source literal was reconstructed by doubling every backslash and single quote, and the
--   result verified to match production's md5(pg_get_functiondef) exactly before being written here.
-- Verified byte-exact against the 2026-09-02 rolled-back dry run; md5 of everything below this header block: 178deacbfa50de38e6b5a18e09bc737b
--   (previous live value 681da577d8e10df55e30c345d284e139 through 2026-08-31; changes ONLY when 20260902220100 is applied).
CREATE OR REPLACE FUNCTION public.af_eligibility_clause()
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$ select E'
    where (s.production_ready or ((p_cities is null or cardinality(p_cities) = 0) and (p_districts is null or cardinality(p_districts) = 0) and p_region_ids is null and not public.search_row_price_gated(s.deal_ar, s.price_total) and (s.region_id is null or s.city_id is null)))
      -- read-side defense-in-depth (2026-08): block only Ezhalah-side impossible/invalid states;
      -- never hides a source price (no magnitude check; 0 legal); production_ready must have a location.
      and coalesce(s.area_m2, 0) >= 0 and coalesce(s.price_total, 0) >= 0 and coalesce(s.price_annual, 0) >= 0
      and s.deal_ar is not null
      and (not s.production_ready or (s.city_id is not null and s.region_id is not null))
      and (p_deal       is null or s.deal_ar = p_deal)
      and (p_rent_period is null
           or s.deal_ar <> ''إيجار''
           or (p_rent_period = ''شهري'' and s.payment_monthly = true and not coalesce(s.rent_now_pay_later, false))
           or (p_rent_period = ''سنوي'' and (s.rent_period_ar = ''سنوي'' or (s.rent_period_ar = ''شهري'' and coalesce(s.rent_now_pay_later, false))))
           or (p_rent_period = ''كلاهما'' and (s.payment_monthly = true or s.rent_period_ar = ''سنوي'' or (s.rent_period_ar = ''شهري'' and coalesce(s.rent_now_pay_later, false))))
           or (p_rent_period not in (''شهري'',''سنوي'',''كلاهما'') and s.rent_period_ar = p_rent_period))
      and (
            ((p_tables is null or s.source_table = any(p_tables))
             and (p_types is null or s.type_ar = any(p_types)))
         or (p_tables2 is not null and p_types2 is not null
             and s.source_table = any(p_tables2)
             and s.type_ar = any(p_types2))
      )
      and (p_category is null
           or exists (
             select 1 from known_type_ar k
             where k.type_ar = s.type_ar
               and (
                 k.macro = p_category
                 or (
                   k.macro = ''both''
                   and (case p_category
                          when ''Residential'' then s.source_table like ''%\\_residential\\_listings''
                          when ''Commercial''  then s.source_table like ''%\\_commercial\\_listings''
                          else true
                        end)
                 )
               )
           ))
      and (p_cities is null or cardinality(p_cities) = 0
           or normalize_ar(s.city_ar) = any (array(select tok from city_tokens))
           or s.city_id = any (array(select city_id from city_ids))
           or s.match_city_ids && (select array_agg(city_id) from city_ids))
      and (p_districts is null or cardinality(p_districts) = 0 or norm_district_tok(s.district_ar) = any (array(select tok from district_tokens)))
      and (p_platforms is null or cardinality(p_platforms) = 0 or s.platform = any(p_platforms))
      -- CARDINALITY CAP (2026-08-15): an oversized array is anon-callable DoS, and a request that
      -- large is never a real user. Fail CLOSED (no rows) rather than burning 20s of DB time.
      and coalesce(cardinality(p_cities), 0)    <= 200
      and coalesce(cardinality(p_districts), 0) <= 500
      and coalesce(cardinality(p_types), 0)     <= 200
      and coalesce(cardinality(p_platforms), 0) <= 100
      and coalesce(cardinality(p_tables), 0)    <= 200
      and (p_region_ids is null or s.region_id = any(p_region_ids))
      and (nullif(p_area_min,0) is null or (s.area_m2 is not null and s.area_m2 >= p_area_min))
      and (nullif(p_area_max,0) is null or (s.area_m2 is not null and s.area_m2 <= p_area_max))
      and ((coalesce(cardinality(p_bath_exact),0) = 0 and p_bath_min is null)
           or (coalesce(cardinality(p_bath_exact),0) > 0 and s.bathrooms = any(p_bath_exact))
           or (p_bath_min is not null and s.bathrooms is not null and s.bathrooms >= p_bath_min))
      and ((coalesce(cardinality(p_beds_exact),0) = 0 and p_beds_min is null) or (coalesce(cardinality(p_beds_exact),0) > 0 and s.bedrooms = any(p_beds_exact)) or (p_beds_min is not null and s.bedrooms >= p_beds_min))
      and (
            (p_deal is null and s.deal_ar = ''بيع''
             and (nullif(p_price_min,0) is null and nullif(p_price_max,0) is null
                  or (s.price_total is not null and s.price_total > 0
                      and s.price_total >= coalesce(p_price_min,0) and s.price_total <= coalesce(nullif(p_price_max,0),1e15))))
         or (p_deal is null and s.deal_ar = ''إيجار''
             and (nullif(p_price_min_rent,0) is null and nullif(p_price_max_rent,0) is null
                  or (s.price_annual is not null and s.price_annual > 0
                      and s.price_annual >= coalesce(p_price_min_rent,0)
                      and s.price_annual <= coalesce(nullif(p_price_max_rent,0),1e15))))
         or (p_deal is not null and nullif(p_price_min,0) is null and nullif(p_price_max,0) is null)
         or (p_deal is not null and s.deal_ar = ''بيع''
               and s.price_total is not null and s.price_total > 0
               and s.price_total >= coalesce(p_price_min,0) and s.price_total <= coalesce(nullif(p_price_max,0),1e15))
         or (p_deal is not null and s.deal_ar = ''إيجار''
               and s.price_annual is not null and s.price_annual > 0
               and s.price_annual >= coalesce(p_price_min,0)*(case when p_rent_period=''شهري'' then 12 else 1 end)
               and s.price_annual <= coalesce(nullif(p_price_max,0),1e15)*(case when p_rent_period=''شهري'' then 12 else 1 end)))
      and (p_furnished  is null or s.furnished = p_furnished)
      and ((p_age_min is null and p_age_max is null)
           or (s.property_age is not null
               and s.property_age >= coalesce(p_age_min, 0) and s.property_age <= coalesce(p_age_max, 32767)))
      and (p_age_unknown is null or (s.property_age is null) = p_age_unknown)
      and (p_is_new_construction is null or (s.property_age = 0) = p_is_new_construction)
      and (p_tenant     is null or s.tenant_ar = p_tenant)
      and (p_directions is null or norm_direction_ar(s.direction_ar) in (select norm_direction_ar(d) from unnest(p_directions) d))
      and (p_has_license is null or (p_has_license and s.license_number is not null))
      and (p_amenities is null or (
               not exists (select 1 from unnest(p_amenities) tok
                           where tok not in (''elevator'',''parking'',''kitchen'',''ac'',''maid_room'',''driver_room'',''private_entrance'',''car_entrance'',''sanitation'',''electricity'',''water_supply'',''gym'',''pool'',''garden'',''balcony'',''laundry_room'',''optical_fibers'',''separate_electricity_meter'',''separate_water_meter'',''furnished'',''rnpl'',''rent_now_pay_later''))
           and (not (''elevator''         = any(p_amenities)) or s.elevator)
           and (not (''parking''          = any(p_amenities)) or s.parking)
           and (not (''kitchen''          = any(p_amenities)) or s.kitchen)
           and (not (''ac''               = any(p_amenities)) or s.air_conditioner)
           and (not (''maid_room''        = any(p_amenities)) or s.maid_room)
           and (not (''driver_room''      = any(p_amenities)) or s.driver_room)
           and (not (''private_entrance'' = any(p_amenities)) or s.private_entrance)
           and (not (''car_entrance''     = any(p_amenities)) or s.car_entrance)
           and (not (''sanitation''       = any(p_amenities)) or s.sanitation)
           and (not (''electricity''      = any(p_amenities)) or s.electricity)
           and (not (''water_supply''     = any(p_amenities)) or s.water_supply)
           and (not (''gym''                          = any(p_amenities)) or s.gym)
           and (not (''pool''                         = any(p_amenities)) or s.pool)
           and (not (''garden''                       = any(p_amenities)) or s.garden)
           and (not (''balcony''                      = any(p_amenities)) or s.balcony)
           and (not (''laundry_room''                 = any(p_amenities)) or s.laundry_room)
           and (not (''optical_fibers''                = any(p_amenities)) or s.optical_fibers)
           and (not (''separate_electricity_meter''    = any(p_amenities)) or s.separate_electricity_meter)
           and (not (''separate_water_meter''          = any(p_amenities)) or s.separate_water_meter)
           and (not (''furnished''        = any(p_amenities)) or s.furnished)
           and (not (''rnpl''             = any(p_amenities) or ''rent_now_pay_later'' = any(p_amenities)) or s.rent_now_pay_later)))
      and ((p_street_width_min is null and p_street_width_max is null)
           or (s.street_width_m is not null
               and s.street_width_m >= coalesce(p_street_width_min, 0) and s.street_width_m <= coalesce(p_street_width_max, 32767)))
      and ((p_floor_min is null and p_floor_max is null)
           or (s.floor_number is not null
               and s.floor_number >= coalesce(p_floor_min, 0) and s.floor_number <= coalesce(p_floor_max, 2147483647)))
      and (p_rating_min is null or s.rating >= p_rating_min)
      and (p_reviews_min is null or s.reviews_count >= p_reviews_min)
      and (p_unit_subtypes is null or cardinality(p_unit_subtypes) = 0 or s.unit_subtype_ar = any(p_unit_subtypes))
'::text $function$
