-- MIRROR of the LIVE production object. NOT a migration — see the full-body-replace rule.
-- Refreshed 2026-08-28 (first capture) by the AF + Trending Data Integrity routine (docs/ops/AF_TRENDING_DATA_INTEGRITY_ENGINEER.md).
--   af_eligibility_clause() is THE canonical Advanced Filter predicate: every AF count surface and
--   the results RPC are generated by concatenating it (rebuild_af_filter_rpcs()), which is exactly
--   why AGENTS.md forbids hand-editing the four AF RPCs. It had NO mirror, so the one predicate a
--   session most needs to read was invisible in the repo — recoverable only by querying production,
--   which an offline barrier and a CI job cannot do. That is how the oracle-vocabulary drift fixed
--   in this same change survived: nothing in the tree stated what tokens the clause accepts.
--   Re-derived verbatim from pg_get_functiondef (base64 round-trip), never hand-transcribed.
-- Verified byte-exact; md5 of everything below this header block: ea24a98d22674dad6398cdff5e2b5e56
--   equals md5(pg_get_functiondef) in production, 8,574 octets both sides, checked 2026-08-28.
-- Re-verified 2026-08-29, unchanged: live md5(pg_get_functiondef) is still
--   ea24a98d22674dad6398cdff5e2b5e56 (length() reports 8,501 characters — the header's octet figure
--   counts bytes, and the body carries multi-byte Arabic literals; the md5 is the equality that
--   matters and it is identical). The re-check was prompted by
--   20260829152534_af_coverage_cliff_watches_real_predicates_with_an_evidence_floor.sql, which
--   READS this clause to derive the columns af_coverage_cliff monitors but does not redefine it.
--   That migration is why the staleness barrier flagged this file: it names the clause, and the
--   barrier deliberately cannot tell "mentions" from "replaces" — so the answer is to re-verify the
--   mirror against production, which is what happened here, never to loosen the barrier.
-- Re-verified 2026-08-30, unchanged again: live md5(pg_get_functiondef) is still
--   ea24a98d22674dad6398cdff5e2b5e56 at 8,501 characters. Flagged for the same reason as the
--   2026-08-29 re-check, by a migration that READS the clause without redefining it:
--   20260830134244_af_template_absorbs_2026_08_29_ranking_so_rebuild_is_a_noop.sql calls
--   af_eligibility_clause() to swap it back out of the live location_search_candidates_ar definition
--   for the __AF_ELIGIBILITY_WHERE__ placeholder, repairing af_rpc_templates so a rebuild is a
--   provable no-op (see docs/ops/af-trending-data-integrity-2026-08-30/). The clause itself is
--   untouched by that work — which is precisely what re-verifying, rather than re-dating, proves.
CREATE OR REPLACE FUNCTION public.af_eligibility_clause()
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$ select E'
    where (s.production_ready or ((p_cities is null or cardinality(p_cities) = 0) and (p_districts is null or cardinality(p_districts) = 0) and p_region_ids is null and not public.search_row_price_gated(s.deal_ar, s.price_total) and (s.region_id is null or s.city_id is null)))
      -- read-side defense-in-depth (2026-08): block only Ezhalah-side impossible/invalid states;
      -- never hides a source price (no magnitude check; 0 legal); production_ready must have a location.
      and coalesce(s.area_m2, 0) >= 0 and coalesce(s.price_total, 0) >= 0 and coalesce(s.price_annual, 0) >= 0
      and s.deal_ar is not null
      and (not s.production_ready or (s.city_id is not null and s.region_id is not null))
      and (p_deal       is null or s.deal_ar = p_deal)
      and (p_rent_period is null
           or s.deal_ar <> ''إيجار''
           or (p_rent_period = ''شهري'' and s.payment_monthly = true and not coalesce(s.rent_now_pay_later, false))
           or (p_rent_period = ''سنوي'' and (s.rent_period_ar = ''سنوي'' or (s.rent_period_ar = ''شهري'' and coalesce(s.rent_now_pay_later, false))))
           or (p_rent_period = ''كلاهما'' and (s.payment_monthly = true or s.rent_period_ar = ''سنوي'' or (s.rent_period_ar = ''شهري'' and coalesce(s.rent_now_pay_later, false))))
           or (p_rent_period not in (''شهري'',''سنوي'',''كلاهما'') and s.rent_period_ar = p_rent_period))
      and (
            ((p_tables is null or s.source_table = any(p_tables))
             and (p_types is null or s.type_ar = any(p_types)))
         or (p_tables2 is not null and p_types2 is not null
             and s.source_table = any(p_tables2)
             and s.type_ar = any(p_types2))
      )
      and (p_category is null
           or exists (
             select 1 from known_type_ar k
             where k.type_ar = s.type_ar
               and (
                 k.macro = p_category
                 or (
                   k.macro = ''both''
                   and (case p_category
                          when ''Residential'' then s.source_table like ''%\\_residential\\_listings''
                          when ''Commercial''  then s.source_table like ''%\\_commercial\\_listings''
                          else true
                        end)
                 )
               )
           ))
      and (p_cities is null or cardinality(p_cities) = 0
           or normalize_ar(s.city_ar) = any (array(select tok from city_tokens))
           or s.city_id = any (array(select city_id from city_ids))
           or s.match_city_ids && (select array_agg(city_id) from city_ids))
      and (p_districts is null or cardinality(p_districts) = 0 or norm_district_tok(s.district_ar) = any (array(select tok from district_tokens)))
      and (p_platforms is null or cardinality(p_platforms) = 0 or s.platform = any(p_platforms))
      -- CARDINALITY CAP (2026-08-15): an oversized array is anon-callable DoS, and a request that
      -- large is never a real user. Fail CLOSED (no rows) rather than burning 20s of DB time.
      and coalesce(cardinality(p_cities), 0)    <= 200
      and coalesce(cardinality(p_districts), 0) <= 500
      and coalesce(cardinality(p_types), 0)     <= 200
      and coalesce(cardinality(p_platforms), 0) <= 100
      and coalesce(cardinality(p_tables), 0)    <= 200
      and (p_region_ids is null or s.region_id = any(p_region_ids))
      and (nullif(p_area_min,0) is null or (s.area_m2 is not null and s.area_m2 >= p_area_min))
      and (nullif(p_area_max,0) is null or (s.area_m2 is not null and s.area_m2 <= p_area_max))
      and ((coalesce(cardinality(p_bath_exact),0) = 0 and p_bath_min is null)
           or (coalesce(cardinality(p_bath_exact),0) > 0 and s.bathrooms = any(p_bath_exact))
           or (p_bath_min is not null and s.bathrooms is not null and s.bathrooms >= p_bath_min))
      and ((coalesce(cardinality(p_beds_exact),0) = 0 and p_beds_min is null) or (coalesce(cardinality(p_beds_exact),0) > 0 and s.bedrooms = any(p_beds_exact)) or (p_beds_min is not null and s.bedrooms >= p_beds_min))
      and (
            (p_deal is null and s.deal_ar = ''بيع''
             and (nullif(p_price_min,0) is null and nullif(p_price_max,0) is null
                  or (s.price_total is not null and s.price_total > 0
                      and s.price_total >= coalesce(p_price_min,0) and s.price_total <= coalesce(nullif(p_price_max,0),1e15))))
         or (p_deal is null and s.deal_ar = ''إيجار''
             and (nullif(p_price_min_rent,0) is null and nullif(p_price_max_rent,0) is null
                  or (s.price_annual is not null and s.price_annual > 0
                      and s.price_annual >= coalesce(p_price_min_rent,0)
                      and s.price_annual <= coalesce(nullif(p_price_max_rent,0),1e15))))
         or (p_deal is not null and nullif(p_price_min,0) is null and nullif(p_price_max,0) is null)
         or (p_deal is not null and s.deal_ar = ''بيع''
               and s.price_total is not null and s.price_total > 0
               and s.price_total >= coalesce(p_price_min,0) and s.price_total <= coalesce(nullif(p_price_max,0),1e15))
         or (p_deal is not null and s.deal_ar = ''إيجار''
               and s.price_annual is not null and s.price_annual > 0
               and s.price_annual >= coalesce(p_price_min,0)*(case when p_rent_period=''شهري'' then 12 else 1 end)
               and s.price_annual <= coalesce(nullif(p_price_max,0),1e15)*(case when p_rent_period=''شهري'' then 12 else 1 end)))
      and (p_furnished  is null or s.furnished = p_furnished)
      and ((p_age_min is null and p_age_max is null)
           or (s.property_age is not null
               and s.property_age >= coalesce(p_age_min, 0) and s.property_age <= coalesce(p_age_max, 32767)))
      and (p_age_unknown is null or (s.property_age is null) = p_age_unknown)
      and (p_is_new_construction is null or (s.property_age = 0) = p_is_new_construction)
      and (p_tenant     is null or s.tenant_ar = p_tenant)
      and (p_directions is null or norm_direction_ar(s.direction_ar) in (select norm_direction_ar(d) from unnest(p_directions) d))
      and (p_has_license is null or (s.license_number is not null) = p_has_license)
      and (p_amenities is null or (
               not exists (select 1 from unnest(p_amenities) tok
                           where tok not in (''elevator'',''parking'',''kitchen'',''ac'',''maid_room'',''driver_room'',''private_entrance'',''car_entrance'',''sanitation'',''electricity'',''water_supply'',''furnished'',''rnpl'',''rent_now_pay_later''))
           and (not (''elevator''         = any(p_amenities)) or s.elevator)
           and (not (''parking''          = any(p_amenities)) or s.parking)
           and (not (''kitchen''          = any(p_amenities)) or s.kitchen)
           and (not (''ac''               = any(p_amenities)) or s.air_conditioner)
           and (not (''maid_room''        = any(p_amenities)) or s.maid_room)
           and (not (''driver_room''      = any(p_amenities)) or s.driver_room)
           and (not (''private_entrance'' = any(p_amenities)) or s.private_entrance)
           and (not (''car_entrance''     = any(p_amenities)) or s.car_entrance)
           and (not (''sanitation''       = any(p_amenities)) or s.sanitation)
           and (not (''electricity''      = any(p_amenities)) or s.electricity)
           and (not (''water_supply''     = any(p_amenities)) or s.water_supply)
           and (not (''furnished''        = any(p_amenities)) or s.furnished)
           and (not (''rnpl''             = any(p_amenities) or ''rent_now_pay_later'' = any(p_amenities)) or s.rent_now_pay_later)))
      and ((p_street_width_min is null and p_street_width_max is null)
           or (s.street_width_m is not null
               and s.street_width_m >= coalesce(p_street_width_min, 0) and s.street_width_m <= coalesce(p_street_width_max, 32767)))
      and ((p_floor_min is null and p_floor_max is null)
           or (s.floor_number is not null
               and s.floor_number >= coalesce(p_floor_min, 0) and s.floor_number <= coalesce(p_floor_max, 2147483647)))
      and (p_rating_min is null or s.rating >= p_rating_min)
      and (p_reviews_min is null or s.reviews_count >= p_reviews_min)
      and (p_unit_subtypes is null or cardinality(p_unit_subtypes) = 0 or s.unit_subtype_ar = any(p_unit_subtypes))
'::text $function$
