// Visible artwork bounds, excluding transparent margins.
// Theme variants keep the same canvas and original artwork geometry.
type ArtworkBounds = readonly [width: number, height: number, left: number, top: number, right: number, bottom: number];
export const platformLogoBounds = new Map<unknown, ArtworkBounds>([
  [require('../../assets/images/abeea.png'), [512, 436, 125, 6, 415, 368]],
  [require('../../assets/images/abralosol.png'), [724, 638, 110, 113, 590, 566]],
  [require('../../assets/images/abwbna.png'), [1276, 992, 409, 151, 867, 834]],
  [require('../../assets/images/akariyoun.png'), [103, 103, 4, 4, 98, 99]],
  [require('../../assets/images/aldarim.png'), [256, 256, 14, 14, 243, 242]],
  [require('../../assets/images/alhoshan.png'), [256, 256, 32, 14, 224, 243]],
  [require('../../assets/images/alhumaidan.png'), [256, 256, 11, 74, 245, 181]],
  [require('../../assets/images/alkhaas.png'), [512, 293, 71, 40, 462, 247]],
  [require('../../assets/images/alnokhba.png'), [371, 512, 60, 6, 335, 496]],
  [require('../../assets/images/alobid.png'), [400, 400, 16, 67, 389, 333]],
  [require('../../assets/images/alta.png'), [1063, 798, 0, 0, 1063, 798]],
  [require('../../assets/images/amaall.png'), [512, 512, 32, 0, 510, 344]],
  [require('../../assets/images/amlakalahsa.png'), [380, 408, 17, 18, 334, 404]],
  [require('../../assets/images/aouj.png'), [246, 138, 61, 20, 224, 108]],
  [require('../../assets/images/aqar-logo.png'), [256, 256, 34, 43, 213, 197]],
  [require('../../assets/images/aqaralsaudia.png'), [276, 268, 64, 35, 256, 229]],
  [require('../../assets/images/aqaratikom.png'), [512, 440, 131, 62, 395, 389]],
  [require('../../assets/images/aqarcity-logo.png'), [256, 256, 13, 101, 243, 156]],
  [require('../../assets/images/aqargate-logo.png'), [256, 256, 13, 22, 242, 234]],
  [require('../../assets/images/aqarnajran.png'), [256, 256, 10, 99, 246, 156]],
  [require('../../assets/images/aqaryoon.png'), [236, 236, 47, 29, 224, 229]],
  [require('../../assets/images/arkaan.png'), [444, 160, 49, 14, 377, 137]],
  [require('../../assets/images/awal.png'), [512, 414, 104, 29, 385, 355]],
  [require('../../assets/images/azdad.png'), [500, 500, 2, 33, 498, 468]],
  [require('../../assets/images/bahadhabab.png'), [500, 500, 105, 101, 394, 404]],
  [require('../../assets/images/compoundin.png'), [256, 256, 10, 94, 246, 162]],
  [require('../../assets/images/dealapp.png'), [512, 206, 16, 34, 493, 194]],
  [require('../../assets/images/eaqartabuk.png'), [256, 256, 57, 13, 199, 242]],
  [require('../../assets/images/eastabha-logo.png'), [256, 256, 30, 13, 226, 243]],
  [require('../../assets/images/erapulse.png'), [439, 512, 20, 7, 397, 464]],
  [require('../../assets/images/fahadalshahri.png'), [256, 256, 28, 40, 229, 216]],
  [require('../../assets/images/fursaghyr.png'), [256, 256, 14, 75, 242, 181]],
  [require('../../assets/images/gathern.png'), [512, 460, 81, 77, 423, 443]],
  [require('../../assets/images/gudai.png'), [256, 256, 10, 15, 246, 240]],
  [require('../../assets/images/hajer-logo.png'), [256, 256, 25, 13, 231, 242]],
  [require('../../assets/images/jazan-watan.png'), [256, 256, 16, 52, 240, 204]],
  [require('../../assets/images/jurash.png'), [462, 512, 30, 191, 265, 424]],
  [require('../../assets/images/ksaaqar.png'), [358, 355, 0, 0, 358, 355]],
  [require('../../assets/images/mizlaj.png'), [256, 256, 15, 79, 241, 177]],
  [require('../../assets/images/muktamel.png'), [256, 256, 47, 15, 209, 240]],
  [require('../../assets/images/mustaqr.png'), [256, 256, 13, 87, 243, 169]],
  [require('../../assets/images/nowaisiry.png'), [511, 512, 102, 6, 433, 437]],
  [require('../../assets/images/october.png'), [512, 435, 53, 23, 450, 384]],
  [require('../../assets/images/platform-placeholder.png'), [256, 256, 56, 66, 201, 206]],
  [require('../../assets/images/raghdan.png'), [256, 256, 14, 58, 242, 197]],
  [require('../../assets/images/rakez.png'), [200, 226, 1, 1, 199, 225]],
  [require('../../assets/images/ramzalqassim.png'), [256, 256, 13, 18, 243, 238]],
  [require('../../assets/images/rawasidark.png'), [568, 492, 108, 0, 456, 473]],
  [require('../../assets/images/remal.png'), [1280, 195, 88, 18, 1204, 179]],
  [require('../../assets/images/sadin.png'), [256, 256, 56, 17, 200, 243]],
  [require('../../assets/images/sadiq-eltajer.png'), [570, 324, 45, 0, 554, 324]],
  [require('../../assets/images/safera.png'), [256, 256, 13, 11, 243, 245]],
  [require('../../assets/images/sanadak-logo.png'), [256, 256, 49, 13, 206, 243]],
  [require('../../assets/images/satel.png'), [256, 256, 13, 23, 243, 233]],
  [require('../../assets/images/shmoualshmal.png'), [207, 294, 0, 1, 205, 291]],
  [require('../../assets/images/souq24.png'), [510, 512, 98, 89, 442, 424]],
  [require('../../assets/images/suwar.png'), [512, 250, 14, 4, 492, 246]],
  [require('../../assets/images/therc.png'), [204, 228, 28, 52, 143, 222]],
  [require('../../assets/images/toor.png'), [256, 256, 13, 78, 243, 178]],
  [require('../../assets/images/wasalt-logo.png'), [256, 256, 64, 29, 193, 228]],
  [require('../../assets/images/wslnaa.png'), [256, 256, 10, 49, 246, 206]],
]);

export const platformLogoContrast = new Map<unknown, { light?: number; dark?: number }>([
  [require('../../assets/images/abeea.png'), { light: require('../../assets/images/platform-contrast/abeea-light.png'), dark: require('../../assets/images/platform-contrast/abeea-dark.png') }],
  [require('../../assets/images/abralosol.png'), { light: require('../../assets/images/platform-contrast/abralosol-light.png') }],
  [require('../../assets/images/abwbna.png'), { light: require('../../assets/images/platform-contrast/abwbna-light.png'), dark: require('../../assets/images/platform-contrast/abwbna-dark.png') }],
  [require('../../assets/images/akariyoun.png'), { light: require('../../assets/images/platform-contrast/akariyoun-light.png') }],
  [require('../../assets/images/aldarim.png'), { light: require('../../assets/images/platform-contrast/aldarim-light.png') }],
  [require('../../assets/images/alhoshan.png'), { dark: require('../../assets/images/platform-contrast/alhoshan-dark.png') }],
  [require('../../assets/images/alhumaidan.png'), { dark: require('../../assets/images/platform-contrast/alhumaidan-dark.png') }],
  [require('../../assets/images/alkhaas.png'), { light: require('../../assets/images/platform-contrast/alkhaas-light.png'), dark: require('../../assets/images/platform-contrast/alkhaas-dark.png') }],
  [require('../../assets/images/alnokhba.png'), { dark: require('../../assets/images/platform-contrast/alnokhba-dark.png') }],
  [require('../../assets/images/alobid.png'), { light: require('../../assets/images/platform-contrast/alobid-light.png'), dark: require('../../assets/images/platform-contrast/alobid-dark.png') }],
  [require('../../assets/images/amaall.png'), { dark: require('../../assets/images/platform-contrast/amaall-dark.png') }],
  [require('../../assets/images/amlakalahsa.png'), { light: require('../../assets/images/platform-contrast/amlakalahsa-light.png') }],
  [require('../../assets/images/aouj.png'), { light: require('../../assets/images/platform-contrast/aouj-light.png'), dark: require('../../assets/images/platform-contrast/aouj-dark.png') }],
  [require('../../assets/images/aqaralsaudia.png'), { dark: require('../../assets/images/platform-contrast/aqaralsaudia-dark.png') }],
  [require('../../assets/images/aqaratikom.png'), { light: require('../../assets/images/platform-contrast/aqaratikom-light.png'), dark: require('../../assets/images/platform-contrast/aqaratikom-dark.png') }],
  [require('../../assets/images/aqarcity-logo.png'), { light: require('../../assets/images/platform-contrast/aqarcity-logo-light.png'), dark: require('../../assets/images/platform-contrast/aqarcity-logo-dark.png') }],
  [require('../../assets/images/aqargate-logo.png'), { light: require('../../assets/images/platform-contrast/aqargate-logo-light.png'), dark: require('../../assets/images/platform-contrast/aqargate-logo-dark.png') }],
  [require('../../assets/images/aqarnajran.png'), { light: require('../../assets/images/platform-contrast/aqarnajran-light.png') }],
  [require('../../assets/images/aqaryoon.png'), { dark: require('../../assets/images/platform-contrast/aqaryoon-dark.png') }],
  [require('../../assets/images/arkaan.png'), { dark: require('../../assets/images/platform-contrast/arkaan-dark.png') }],
  [require('../../assets/images/awal.png'), { dark: require('../../assets/images/platform-contrast/awal-dark.png') }],
  [require('../../assets/images/azdad.png'), { light: require('../../assets/images/platform-contrast/azdad-light.png'), dark: require('../../assets/images/platform-contrast/azdad-dark.png') }],
  [require('../../assets/images/bahadhabab.png'), { light: require('../../assets/images/platform-contrast/bahadhabab-light.png'), dark: require('../../assets/images/platform-contrast/bahadhabab-dark.png') }],
  [require('../../assets/images/compoundin.png'), { dark: require('../../assets/images/platform-contrast/compoundin-dark.png') }],
  [require('../../assets/images/dealapp.png'), { light: require('../../assets/images/platform-contrast/dealapp-light.png') }],
  [require('../../assets/images/eaqartabuk.png'), { light: require('../../assets/images/platform-contrast/eaqartabuk-light.png') }],
  [require('../../assets/images/eastabha-logo.png'), { light: require('../../assets/images/platform-contrast/eastabha-logo-light.png'), dark: require('../../assets/images/platform-contrast/eastabha-logo-dark.png') }],
  [require('../../assets/images/erapulse.png'), { light: require('../../assets/images/platform-contrast/erapulse-light.png') }],
  [require('../../assets/images/fahadalshahri.png'), { light: require('../../assets/images/platform-contrast/fahadalshahri-light.png') }],
  [require('../../assets/images/fursaghyr.png'), { light: require('../../assets/images/platform-contrast/fursaghyr-light.png') }],
  [require('../../assets/images/gathern.png'), { light: require('../../assets/images/platform-contrast/gathern-light.png') }],
  [require('../../assets/images/gudai.png'), { light: require('../../assets/images/platform-contrast/gudai-light.png') }],
  [require('../../assets/images/hajer-logo.png'), { light: require('../../assets/images/platform-contrast/hajer-logo-light.png'), dark: require('../../assets/images/platform-contrast/hajer-logo-dark.png') }],
  [require('../../assets/images/jazan-watan.png'), { light: require('../../assets/images/platform-contrast/jazan-watan-light.png'), dark: require('../../assets/images/platform-contrast/jazan-watan-dark.png') }],
  [require('../../assets/images/jurash.png'), { light: require('../../assets/images/platform-contrast/jurash-light.png') }],
  [require('../../assets/images/mizlaj.png'), { dark: require('../../assets/images/platform-contrast/mizlaj-dark.png') }],
  [require('../../assets/images/muktamel.png'), { dark: require('../../assets/images/platform-contrast/muktamel-dark.png') }],
  [require('../../assets/images/mustaqr.png'), { light: require('../../assets/images/platform-contrast/mustaqr-light.png') }],
  [require('../../assets/images/nowaisiry.png'), { dark: require('../../assets/images/platform-contrast/nowaisiry-dark.png') }],
  [require('../../assets/images/october.png'), { light: require('../../assets/images/platform-contrast/october-light.png'), dark: require('../../assets/images/platform-contrast/october-dark.png') }],
  [require('../../assets/images/platform-placeholder.png'), { dark: require('../../assets/images/platform-contrast/platform-placeholder-dark.png') }],
  [require('../../assets/images/raghdan.png'), { light: require('../../assets/images/platform-contrast/raghdan-light.png'), dark: require('../../assets/images/platform-contrast/raghdan-dark.png') }],
  [require('../../assets/images/rakez.png'), { light: require('../../assets/images/platform-contrast/rakez-light.png') }],
  [require('../../assets/images/rawasidark.png'), { dark: require('../../assets/images/platform-contrast/rawasidark-dark.png') }],
  [require('../../assets/images/remal.png'), { light: require('../../assets/images/platform-contrast/remal-light.png') }],
  [require('../../assets/images/sadin.png'), { light: require('../../assets/images/platform-contrast/sadin-light.png') }],
  [require('../../assets/images/sadiq-eltajer.png'), { light: require('../../assets/images/platform-contrast/sadiq-eltajer-light.png') }],
  [require('../../assets/images/safera.png'), { light: require('../../assets/images/platform-contrast/safera-light.png') }],
  [require('../../assets/images/sanadak-logo.png'), { light: require('../../assets/images/platform-contrast/sanadak-logo-light.png') }],
  [require('../../assets/images/satel.png'), { light: require('../../assets/images/platform-contrast/satel-light.png') }],
  [require('../../assets/images/shmoualshmal.png'), { dark: require('../../assets/images/platform-contrast/shmoualshmal-dark.png') }],
  [require('../../assets/images/souq24.png'), { dark: require('../../assets/images/platform-contrast/souq24-dark.png') }],
  [require('../../assets/images/suwar.png'), { light: require('../../assets/images/platform-contrast/suwar-light.png') }],
  [require('../../assets/images/therc.png'), { light: require('../../assets/images/platform-contrast/therc-light.png'), dark: require('../../assets/images/platform-contrast/therc-dark.png') }],
  [require('../../assets/images/toor.png'), { light: require('../../assets/images/platform-contrast/toor-light.png') }],
  [require('../../assets/images/wasalt-logo.png'), { dark: require('../../assets/images/platform-contrast/wasalt-logo-dark.png') }],
  [require('../../assets/images/wslnaa.png'), { dark: require('../../assets/images/platform-contrast/wslnaa-dark.png') }],
]);
