import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useI18n, LOCALE_KEY, getLocale, setLocalePersistence, type Locale } from '@/i18n';
import { emptyQuery, runSearch, queryLabel, type SearchQuery, type SearchResult } from '@/data/search';
import { buildPools, type Listing } from '@/data/listings';
import { fetchListingsForQuery, fetchListingById, getCachedListing } from '@/data/remote';
import { resolveLocation, ensureLocationIndex } from '@/data/locations';
import { trackClick } from '@/data/clicks';
import { supabase } from '@/lib/supabase';
import { mapSupabaseUser, signOutBackend } from '@/lib/auth';
import { buildSyncedName } from '@/lib/nameSync';

type DataSource = 'local' | 'supabase';

export type AuthUser = {
  method: 'phone' | 'google' | 'apple';
  name: string; // the name as the user last typed it (canonical)
  // Bilingual spellings, kept synced: Arabic UI shows nameAr, English UI shows nameEn. Generated by
  // the `translit` backend when the user edits their name in either script. (see lib/nameSync.)
  nameEn?: string;
  nameAr?: string;
  initials: string;
  sub: string; // phone or email
};

export type HistoryItem = { id: string; label: string; query: SearchQuery; ts: number; starred?: boolean };

type AppState = {
  query: SearchQuery;
  setQuery: (updater: (q: SearchQuery) => SearchQuery) => void;
  resetQuery: () => void;
  runQuery: (q: SearchQuery, record?: boolean) => Promise<SearchResult>;
  dataSource: DataSource;
  // Auth + the post-first-search gate (PRD §9): the first search is free; anything beyond it
  // requires sign-in. `gated` is true once a guest has used their one free search.
  user: AuthUser | null;
  signIn: (u: AuthUser) => void;
  updateUser: (patch: Partial<AuthUser>) => void;
  signOut: () => void;
  // Permanently delete the account: wipe ALL on-device state (history, parked message, saved
  // language) from both memory AND storage, then sign out. Distinct from signOut, which keeps the
  // saved history in storage so a later re-login restores it. (user request: after deletion nothing
  // from the old account must come back.)
  deleteAccount: () => void;
  searchCount: number;
  gated: boolean;
  // A message the user typed but couldn't send because the gate fired. Persisted so it survives the
  // whole auth round-trip — including a full page reload during a real OAuth redirect — so after
  // sign-in the chat can replay it. The user never loses what they wrote or has to start over.
  pendingMessage: string | null;
  setPendingMessage: (m: string | null) => void;
  // CPC tracking (PRD §13): log a click-through whenever the user opens a partner listing.
  trackOpen: (listing: Listing) => void;
  // Resolve a listing by id from the live (Supabase-hydrated) catalog, so the in-app
  // browser opens real ingested listings — not just the bundled seed ids.
  findListing: (id: number) => Promise<Listing | undefined>;
  // Search history (PRD §13: retained until account deletion). Most-recent first.
  history: HistoryItem[];
  clearHistory: () => void;
  toggleStar: (id: string) => void;
  deleteHistory: (id: string) => void;
  // Record a free-text user message as the active chat's sidebar entry. First message → creates a
  // new chat in Recent with the user's text as the title; subsequent messages → update the same
  // chat's title to the LATEST user text and bump it to the top. Signed-in users only — a guest's
  // chat-only conversations are session-only. Returns the chat id used. (user request.)
  recordChatTurn: (text: string) => string | null;
  // Which history chat is currently open, so the sidebar can highlight it (light green) and the user
  // always knows which conversation they're in. `null` on Home / New Chat (no chat selected).
  activeChatId: string | null;
  setActiveChat: (id: string | null) => void;
  // Support / About Us are shown as in-app popups (centered dialog over a dimmed page) rather than
  // full-screen routes, so they open from the drawer without navigating away.
  modal: 'support' | 'about' | null;
  openModal: (m: 'support' | 'about') => void;
  closeModal: () => void;
  // First-run cinematic intro (the eagle clip). Shows ONCE, only for a brand-new logged-out
  // visitor; persisted via a `hasSeenIntro` flag so it never replays. `showIntro` waits until both
  // the saved flag is read AND the auth session is resolved, so it never flashes for a returning
  // signed-in user. `dismissIntro` is called when the video finishes (or fails, as a safety).
  showIntro: boolean;
  dismissIntro: () => void;
};

const Ctx = createContext<AppState | null>(null);

// When true, the intro replays on every logged-out load (and the "seen" flag isn't persisted) so it
// can be re-watched while previewing. Production behaviour is false → shows once, first run only.
const INTRO_DEMO_MODE = false;

// History is stored PER ACCOUNT, keyed by the user's identity (phone/email), NOT under one shared
// key. A single global 'history' key leaked across sessions: logging into a different account — or
// back in after a delete — would resurrect the previous searches. Scoping by `sub` keeps each
// account's chats isolated, so a fresh login starts clean and a deleted account stays deleted.
const historyKey = (sub: string) => 'history:' + sub;
// The old shared key. We proactively purge it so its stale, cross-account contents never reappear.
const LEGACY_HISTORY_KEY = 'history';

export function AppProvider({ children }: { children: ReactNode }) {
  // The FILTER (home) defaults to Buy highlighted (user request). emptyQuery() stays Rent-default for
  // the agent/chat base — this override is only the filter form's starting state.
  const [query, setQueryState] = useState<SearchQuery>({ ...emptyQuery(), deal: 'Buy' });
  // Ezhalah is a pure aggregator showing only REAL scraped listings. There's no whole-table load
  // anymore — each search fetches its own matching subset from Supabase (see runQuery →
  // fetchListingsForQuery). dataSource is constant 'supabase' (kept for any UI that reads it).
  const dataSource: DataSource = 'supabase';
  const [user, setUser] = useState<AuthUser | null>(null);
  const [searchCount, setSearchCount] = useState(0);
  // Keep the user's name bilingual: when we only know one script (e.g. Google gives a Latin name),
  // generate the other once in the background so the Arabic UI can show the Arabic spelling without
  // waiting for the user to edit. Runs at most once per distinct name. (see lib/nameSync.)
  const nameSyncRef = useRef('');
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const [modal, setModal] = useState<'support' | 'about' | null>(null);
  const [pendingMessage, setPendingMessageState] = useState<string | null>(null);
  // `null` while the saved flag is still being read from storage; the intro stays hidden until then.
  const [introSeen, setIntroSeen] = useState<boolean | null>(null);
  // True once we know the auth state (session restored or confirmed absent), so the intro decision
  // doesn't race the Supabase session lookup and flash for a returning signed-in user.
  const [authChecked, setAuthChecked] = useState(false);

  // Backfill the missing-script spelling of the user's name (once per name) so both stay synced.
  useEffect(() => {
    const nm = user?.name?.trim();
    if (!nm || (user?.nameEn && user?.nameAr)) return;
    if (nameSyncRef.current === nm) return;
    nameSyncRef.current = nm;
    let cancelled = false;
    buildSyncedName(nm).then((synced) => {
      if (!cancelled) setUser((u) => (u && u.name === synced.name ? { ...u, ...synced } : u));
    });
    return () => { cancelled = true; };
  }, [user?.name, user?.nameEn, user?.nameAr]);

  // Language persistence is auth-gated. A SIGNED-IN user keeps their chosen/detected language across a
  // refresh. A GUEST is ALWAYS Arabic-first on a fresh load — typing an English letter in the filter,
  // or sending an English message to the agent, flips the UI live for that session, but a refresh /
  // leaving resets to the Arabic default (nothing is saved). On WEB the signed-in language is applied
  // synchronously at first paint (i18n readSavedLocale, no flash); the effects below cover NATIVE and
  // enforce the guest reset. (user request.)
  const { locale, setLocale } = useI18n();
  const localeInitRef = useRef(false);
  const historyLoadedRef = useRef(false);

  // React to auth state: signed-in → enable persistence + restore the saved language once; guest →
  // disable persistence, clear any saved value, and snap back to the Arabic default for this load.
  useEffect(() => {
    if (!authChecked) return;
    if (user) {
      setLocalePersistence(true);
      if (!localeInitRef.current) {
        localeInitRef.current = true;
        AsyncStorage.getItem(LOCALE_KEY)
          .then((v) => { if (v === 'en' || v === 'ar') setLocale(v as Locale); })
          .catch(() => {});
      }
    } else {
      setLocalePersistence(false); // guest → never remember the language
      localeInitRef.current = false;
      AsyncStorage.removeItem(LOCALE_KEY).catch(() => {});
      // Fresh guest load (or just logged out): start in Arabic. This runs only when auth state changes,
      // not on every locale change, so a guest's in-session switch to English is left untouched.
      if (getLocale() !== 'ar') setLocale('ar');
    }
  }, [authChecked, user, setLocale]);

  // Persist the active language ONLY for a signed-in user (native; web persists synchronously via the
  // auth-gated persistLocale in setLocale). A guest never writes their language.
  useEffect(() => {
    if (!user) return;
    AsyncStorage.setItem(LOCALE_KEY, locale).catch(() => {});
  }, [locale, user]);

  // Restore saved chats on launch. SIGNED-IN users hydrate from their own bucket; GUESTS hydrate
  // from a separate `history:guest` bucket so things like a starred chat survive a refresh in the
  // same browser. (user request: click star → refresh → star still there.)
  useEffect(() => {
    if (!authChecked) return;
    if (historyLoadedRef.current) return;
    historyLoadedRef.current = true;
    // Purge the legacy shared key once — it's the source of the cross-account leak. From here on,
    // history lives only under this account's own key.
    AsyncStorage.removeItem(LEGACY_HISTORY_KEY).catch(() => {});
    const key = historyKey(user ? user.sub : 'guest');
    AsyncStorage.getItem(key)
      .then((v) => {
        if (!v) return;
        try {
          const saved = JSON.parse(v);
          if (Array.isArray(saved)) setHistory(saved as HistoryItem[]);
        } catch {}
      })
      .catch(() => {});
  }, [authChecked, user]);

  // Persist chats — for signed-in users under their own key, for guests under the shared `guest` key.
  // Writes localStorage DIRECTLY (synchronous) on web so a refresh immediately after a star/delete can
  // never lose the change. AsyncStorage on native handles the same job. (user-reported persistence bug.)
  useEffect(() => {
    if (!historyLoadedRef.current) return;
    const key = historyKey(user ? user.sub : 'guest');
    const json = JSON.stringify(history);
    try {
      if (typeof localStorage !== 'undefined') localStorage.setItem(key, json);
    } catch {}
    AsyncStorage.setItem(key, json).catch(() => {});
  }, [history, user]);

  // Read the one-time "already saw the intro" flag on launch. In demo mode we ignore any stored flag
  // so the intro shows on every fresh load (and can be re-watched by refreshing).
  useEffect(() => {
    if (INTRO_DEMO_MODE) {
      setIntroSeen(false);
      return;
    }
    AsyncStorage.getItem('hasSeenIntro')
      .then((v) => setIntroSeen(v === '1'))
      .catch(() => setIntroSeen(false));
  }, []);

  // Restore a message that was parked at the gate before a previous sign-in attempt, so it survives
  // an OAuth page reload. The chat consumes and clears it once the user is signed back in.
  useEffect(() => {
    AsyncStorage.getItem('pendingMessage')
      .then((v) => { if (v) setPendingMessageState(v); })
      .catch(() => {});
  }, []);

  // Record a search into history. De-dupe by the QUERY itself (deal/location/category/type/detail/
  // price) rather than the label text — so the same search recorded again, even after the UI language
  // flipped (which changes the label string), updates the one existing chat instead of spawning a
  // duplicate. The freshly-recorded chat becomes the active one (highlighted in the sidebar).
  const sj = (v: unknown) => JSON.stringify(v ?? null);
  const sameQuery = (a: SearchQuery, b: SearchQuery) =>
    a.deal === b.deal && a.location.trim() === b.location.trim() && a.category === b.category &&
    a.type === b.type && a.detail === b.detail && a.priceBand === b.priceBand &&
    a.priceInput === b.priceInput && a.typeGroup === b.typeGroup &&
    sj(a.types) === sj(b.types) && sj(a.contextBedsList) === sj(b.contextBedsList) &&
    a.contextBeds === b.contextBeds && a.contextSize === b.contextSize &&
    a.areaMin === b.areaMin && a.areaMax === b.areaMax &&
    a.priceMin === b.priceMin && a.priceMax === b.priceMax &&
    sj(a.districts) === sj(b.districts);
  // If the user already has a chat for this query, KEEP it (its id and its starred flag) — just
  // refresh the label/timestamp and bump it to the top. Without this, re-running the same search was
  // creating a brand-new entry and silently nuking the star. (user-reported bug.)
  const recordHistory = (q: SearchQuery) => {
    const label = queryLabel(q);
    setHistory((h) => {
      const prior = h.find((it) => sameQuery(it.query, q));
      const id = prior?.id ?? 'h' + Date.now();
      const starred = prior?.starred ?? false;
      const next: HistoryItem = { id, label, query: q, ts: Date.now(), starred };
      setActiveChatId(id);
      const rest = h.filter((it) => it.id !== id);
      return [next, ...rest].slice(0, 50);
    });
  };

  // No startup catalog load anymore. Downloading the whole table (now 21k+ rows, ~47MB) timed out
  // and broke search. Each search fetches only its matching subset from Supabase via runQuery →
  // fetchListingsForQuery. (user-reported: app stuck on "Loading listings".)

  // Real auth: adopt an existing Supabase session on launch and keep `user` in sync
  // with the backend (covers OAuth redirects bouncing back to /auth and token refresh).
  useEffect(() => {
    if (!supabase) {
      setAuthChecked(true); // no backend → there is no session to wait for
      return;
    }
    let cancelled = false;
    supabase.auth.getSession().then(({ data }) => {
      const su = data.session?.user;
      if (!cancelled && su) {
        const method = (su.app_metadata?.provider as AuthUser['method']) ?? 'phone';
        setUser(mapSupabaseUser(su, method === 'google' || method === 'apple' ? method : 'phone'));
      }
      if (!cancelled) setAuthChecked(true);
    });
    const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => {
      const su = session?.user;
      if (su) {
        const method = (su.app_metadata?.provider as AuthUser['method']) ?? 'phone';
        setUser(mapSupabaseUser(su, method === 'google' || method === 'apple' ? method : 'phone'));
      } else {
        setUser(null);
      }
    });
    return () => sub.subscription.unsubscribe();
  }, []);

  const value = useMemo<AppState>(
    () => ({
      query,
      setQuery: (updater) => setQueryState((q) => updater(q)),
      resetQuery: () => setQueryState(emptyQuery()),
      dataSource,
      user,
      searchCount,
      // Guests are NOT gated: they can run as many searches as they like within their session/chat.
      // The only difference from a signed-in user is that nothing is saved — a guest's chats live in
      // memory only and are gone when they leave (no persistence; see the history effects). The
      // incentive to sign in is keeping your searches, not unlocking them. (user request.)
      gated: false,
      pendingMessage,
      setPendingMessage: (m) => {
        setPendingMessageState(m);
        if (m) AsyncStorage.setItem('pendingMessage', m).catch(() => {});
        else AsyncStorage.removeItem('pendingMessage').catch(() => {});
      },
      signIn: (u) => setUser(u),
      updateUser: (patch) => setUser((u) => (u ? { ...u, ...patch } : u)),
      signOut: () => {
        // Drop the session from MEMORY so the next guest never sees the previous user's chats: clear
        // history, search count, the open chat, and any parked message. This account's OWN saved
        // history (under its per-user key) is intentionally KEPT — a later re-login restores it
        // (restore flag reset so it can reload). The legacy shared key is purged so it can't leak.
        setUser(null);
        setHistory([]);
        setSearchCount(0);
        setActiveChatId(null);
        setPendingMessageState(null);
        // Also wipe the GUEST bucket, so the freshly-logged-out guest doesn't inherit the prior
        // signed-in user's in-memory chats getting re-written under 'history:guest'. (user request.)
        AsyncStorage.multiRemove(['pendingMessage', LEGACY_HISTORY_KEY, historyKey('guest')]).catch(() => {});
        historyLoadedRef.current = false;
        void signOutBackend();
      },
      deleteAccount: () => {
        // Permanent: wipe everything tied to THIS account from storage AND memory, then sign out.
        // After this, signing in again — even with the same provider — starts truly fresh: none of
        // the old history, parked message, or saved language comes back. (user request: deleted
        // account must not resurrect its data.)
        const keys = ['pendingMessage', 'locale', LEGACY_HISTORY_KEY];
        if (user) keys.push(historyKey(user.sub));
        AsyncStorage.multiRemove(keys).catch(() => {});
        setUser(null);
        setHistory([]);
        setSearchCount(0);
        setActiveChatId(null);
        setPendingMessageState(null);
        historyLoadedRef.current = false;
        void signOutBackend();
      },
      // `record` defaults to true: a genuine new search adds a history chat. Reopening a saved chat
      // passes record=false so just VIEWING it never spawns a fresh entry — a new chat is only made
      // by a new filter search / chat message (or New Chat), keeping the list clean. (user request.)
      runQuery: async (q, record = true) => {
        // A Room is always exactly 1 bedroom — normalize here so every path (filter or AI agent)
        // shows "1 bedroom" and uses the room price ladder, no matter what detail came in. (user request.)
        if (q.type === 'Room') q = { ...q, detail: '1' };
        // ONE LOCATION ENGINE (user: same resolution everywhere). The FILTER path resolves location up
        // front and attaches q.locationMatch. The AI-CHAT path does NOT — Gemini returns a raw city
        // string that may be a typo or homophone ("Rakk"→Al Rakah, "القرص"→Ar Rass), which dead-ended
        // at "no results". Resolve it HERE, through the SAME resolver the filter uses, so a near miss
        // still finds the real city and the Search Summary shows the corrected Region → City → District.
        if (!q.locationMatch && q.location && q.location.trim()) {
          try {
            await ensureLocationIndex();
            const lm = resolveLocation(q.location, getLocale());
            if (lm.kind !== 'none') {
              const display =
                lm.kind === 'district' || lm.kind === 'city' || lm.kind === 'region' ? lm.label : (lm.city || q.location);
              let districts = q.districts;
              if (lm.kind === 'district') {
                districts = lm.districts.length ? lm.districts : (lm.label ? [lm.label] : districts);
              } else if (lm.kind === 'area' || lm.kind === 'landmark' || lm.kind === 'geography' || lm.kind === 'lifestyle') {
                const clean = lm.districts.filter(Boolean);
                if (clean.length) districts = clean;
              }
              q = { ...q, location: display, locationMatch: lm, districts };
            }
          } catch { /* fall back to the raw location — never hard-fail the search */ }
        }
        // Fetch ONLY this query's matching subset from Supabase (city + type + deal pushed server-side),
        // then run the full client engine on it. Replaces the old "load the whole table" approach that
        // timed out at 21k+ rows. null = backend error (flag it so the UI shows retry, not "no matches").
        const rows = await fetchListingsForQuery(q);
        // Repeat-visit rotation offset: a per-filter counter persisted in localStorage so returning to the
        // SAME filter (deal + location/districts) later surfaces a DIFFERENT high-quality first 25, never the
        // exact same set — while staying strictly inside the filters. Device-local (guests included);
        // best-effort (no localStorage → offset 0, no rotation). (user 2026-06-27.)
        let visitOffset = 0;
        try {
          const sig = `ezh_rot:${q.deal}|${q.regionPin ?? ''}|${(q.districts ?? []).join(',')}|${(q.location ?? '').trim()}`;
          const ls = (globalThis as { localStorage?: { getItem(k: string): string | null; setItem(k: string, v: string): void } }).localStorage;
          const prev = parseInt(ls?.getItem(sig) ?? '0', 10);
          visitOffset = Number.isFinite(prev) ? prev : 0;
          ls?.setItem(sig, String(visitOffset + 1));
        } catch { /* no localStorage (SSR/native) → no rotation, fine */ }
        const r = runSearch(q, buildPools(rows ?? []), { fetchFailed: rows === null, visitOffset });
        if (record) {
          setSearchCount((c) => c + 1);
          // Record the chat in memory (it shows in the current session). Persistence only happens for
          // signed-in users — a guest's chats are never written to storage, so they vanish on leave.
          recordHistory(q);
        }
        // Attach the RESOLVED query so the caller renders the Search Summary from what actually ran
        // (the corrected city/region), not the raw pre-resolution text. (one-engine summary parity.)
        return { ...r, query: q };
      },
      trackOpen: (listing) => {
        void trackClick(listing, user?.sub ?? null);
      },
      findListing: async (id) => {
        // Try the session cache (every searched/opened listing is cached), else fetch the single row.
        const cached = getCachedListing(id);
        if (cached) return cached;
        return (await fetchListingById(id)) ?? undefined;
      },
      history,
      clearHistory: () => setHistory([]),
      // Toggle/delete write to storage SYNCHRONOUSLY in addition to the React effect — so a refresh
      // immediately after the click can't lose the change (the useEffect persist is async; localStorage
      // is sync). Functional setHistory + the computed next array keep state and storage in lock-step.
      // (user-reported bug: starring then refreshing was losing the star.)
      toggleStar: (id) =>
        setHistory((h) => {
          const next = h.map((it) => (it.id === id ? { ...it, starred: !it.starred } : it));
          try {
            const k = historyKey(user ? user.sub : 'guest');
            if (typeof localStorage !== 'undefined') localStorage.setItem(k, JSON.stringify(next));
          } catch {}
          return next;
        }),
      deleteHistory: (id) =>
        setHistory((h) => {
          const next = h.filter((it) => it.id !== id);
          try {
            const k = historyKey(user ? user.sub : 'guest');
            if (typeof localStorage !== 'undefined') localStorage.setItem(k, JSON.stringify(next));
          } catch {}
          return next;
        }),
      // Free-text chat → sidebar Recent entry. Signed-in only (guests don't get sidebar history for
      // chat-only messages). On the first user message of a chat, create a new entry titled with
      // the user's exact text; subsequent messages in the same chat update the title to the LATEST
      // message and bump it to the top of Recent. (user request.)
      recordChatTurn: (text: string): string | null => {
        if (!user) return null;
        const v = (text ?? '').trim();
        if (!v) return null;
        const id = activeChatId ?? 'h' + Date.now();
        setHistory((h) => {
          const idx = h.findIndex((it) => it.id === id);
          let next: HistoryItem[];
          if (idx >= 0) {
            const prev = h[idx];
            const updated: HistoryItem = { ...prev, label: v, ts: Date.now() };
            next = [updated, ...h.filter((it) => it.id !== id)];
          } else {
            const entry: HistoryItem = { id, label: v, query: emptyQuery(), ts: Date.now() };
            next = [entry, ...h].slice(0, 50);
          }
          try {
            const k = historyKey(user.sub);
            if (typeof localStorage !== 'undefined') localStorage.setItem(k, JSON.stringify(next));
          } catch {}
          return next;
        });
        if (activeChatId !== id) setActiveChatId(id);
        return id;
      },
      activeChatId,
      setActiveChat: (id) => setActiveChatId(id),
      modal,
      openModal: (m) => setModal(m),
      closeModal: () => setModal(null),
      showIntro: introSeen === false && authChecked && !user,
      dismissIntro: () => {
        setIntroSeen(true); // session-only hide so it doesn't re-loop after the dissolve
        if (!INTRO_DEMO_MODE) AsyncStorage.setItem('hasSeenIntro', '1').catch(() => {});
      },
    }),
    [query, dataSource, user, searchCount, history, modal, introSeen, authChecked, pendingMessage, activeChatId, setActiveChatId],
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useApp(): AppState {
  const v = useContext(Ctx);
  if (!v) throw new Error('useApp must be used within AppProvider');
  return v;
}
