import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useI18n, LOCALE_KEY, getLocale, setLocalePersistence, type Locale } from '@/i18n';
import { emptyQuery, runSearch, queryLabel, type SearchQuery, type SearchResult } from '@/data/search';
import { HOME_DEFAULT_QUERY, migrateGroups } from '@/lib/searchDefaults';
import { isSameSavedSearch } from '@/lib/savedSearchIdentity';
import { applyMove, applyStarMove } from '@/lib/sidebarReorder';
import { autoTitleForQuery, autoTitleForPrompt, canAutoRetitle, type TitleSource } from '@/lib/chatTitle';
import { dismissalOutlivesTransition } from '@/lib/authPopupBehavior';
import { buildPools, type Listing } from '@/data/listings';
import { fetchListingsForQuery, fetchListingById, getCachedListing } from '@/data/remote';
import { resolveLocation, ensureLocationIndex } from '@/data/locations';
import { trackClick } from '@/data/clicks';
import { supabase } from '@/lib/supabase';
import { mapSupabaseUser, signOutBackend, deleteAccountBackend } from '@/lib/auth';
import { setThemeAuthState, resetThemeForSignOut } from '@/theme/theme';
import { restoreChat, LOCAL_TRANSCRIPT_ENTRIES, type PersistedChat } from '@/lib/chatTranscript';
import { loadChatMetas, fetchChatTranscript, upsertChat, deleteChats, deleteAllChats, type ChatMeta } from '@/lib/chatSync';
import { mergeOne, pickTranscript, withFreshTranscript } from '@/lib/chatMerge';
import { buildSyncedName } from '@/lib/nameSync';
import { identifyUser } from '@/lib/observability';

type DataSource = 'local' | 'supabase';

export type AuthUser = {
  method: 'phone' | 'google' | 'apple';
  name: string; // the name as the user last typed it (canonical)
  // Bilingual spellings, kept synced: Arabic UI shows nameAr, English UI shows nameEn. Generated by
  // the `translit` backend when the user edits their name in either script. (see lib/nameSync.)
  nameEn?: string;
  nameAr?: string;
  initials: string;
  sub: string; // phone or email
};

// snapshot = the results the search actually returned, saved WITH the entry so reopening a saved
// chat renders instantly with zero network (owner 2026-08-14: "it should already show him the
// property... this is just saved"). Capped at SNAPSHOT_CAP cards; «عرض المزيد» continues live
// (loadMore de-dups against the held cards, so a truncated snapshot pages gap-free).
// `title` + `titleSource` are the DISPLAY layer and nothing more (owner 2026-08-21): a title is
// metadata, never identity. Saved-search de-duplication is savedSearchIdentity.ts's job and is
// deliberately not coupled to it — two entries may carry the same title, and renaming one must not
// merge, split or alter any search. `label` is still written so a browser holding an older cached
// bundle (which reads `label`) keeps showing something sensible during a rollout; `title` wins
// wherever both exist. `titleUpdatedAt` records only when the LABEL changed — `ts` continues to
// mean "when this search last ran" and a rename must never move it.
export type HistoryItem = {
  id: string; label: string; query: SearchQuery; ts: number; starred?: boolean; snapshot?: SearchResult;
  title?: string; titleSource?: TitleSource; titleUpdatedAt?: number;
  // FULL CONVERSATION (owner 2026-08-25, ChatGPT-grade persistence): the exact conversation this
  // chat last showed — every bubble, results turn, AF round receipt, revealed page — serialized by
  // src/lib/chatTranscript.ts. Reopening the chat renders THIS, not a 2-message reconstruction.
  // `tRev` stamps the transcript's last change so server sync pushes only real transcript updates
  // (deliberately separate from `ts`: revealing more cards must not resort the sidebar).
  transcript?: PersistedChat;
  tRev?: number;
  // MANUAL SIDEBAR POSITION (owner 2026-08-24, press-hold-drag reorder). Display rank is
  // `order ?? ts` descending — absent on legacy items (timestamp order, unchanged), stamped by a
  // drag (midpoint between neighbours), and DROPPED again when the chat has new activity so the
  // "most recent activity first" contract (Note #9) still wins over an old manual slot. Rides the
  // existing per-account persistence untouched: it is just another field in the stored JSON.
  order?: number;
};

type AppState = {
  query: SearchQuery;
  setQuery: (updater: (q: SearchQuery) => SearchQuery) => void;
  resetQuery: () => void;
  // New Chat = a genuinely fresh session. ONE owner for that reset, so callers never have to know
  // which pieces of shared state a chat leaves behind (owner rule 2026-08-20).
  newChat: () => void;
  // `signal` (owner 2026-08-18, Stop button): when the caller's turn is cancelled, the underlying
  // network calls abort AND the history/searchCount writes are skipped — see the guard at the call site.
  // `chatId` (owner 2026-08-25, conversation identity): a turn that CONTINUES an existing chat —
  // an AF round, a refine chip, Show More context, a follow-up message — passes the chat's id so
  // the record updates THAT entry. Without it, every narrowed query minted a brand-new sidebar
  // entry (savedSearchIdentity treats any AF answer as a different search), which is exactly how a
  // conversation's rounds were scattered across rows and «returning to the chat» lost them.
  runQuery: (q: SearchQuery, record?: boolean, signal?: AbortSignal, chatId?: string | null) => Promise<SearchResult>;
  // Persist the serialized conversation for a chat (agent.tsx captures it after each settled turn).
  saveTranscript: (id: string, transcript: PersistedChat) => void;
  // Fetch a transcript this device no longer holds locally (pruned cache / fresh sign-in) from the
  // server, validate it, and attach it to the entry. Resolves to the transcript or null.
  hydrateTranscript: (id: string) => Promise<PersistedChat | null>;
  loadMoreListings: (q: SearchQuery, offset: number) => Promise<{ listings: Listing[]; nextOffset: number; hasMore: boolean }>;
  dataSource: DataSource;
  // Auth. SEARCH IS FREE, ALWAYS (owner rule 2026-08-15, retiring the PRD §9 gate): a guest can run
  // unlimited searches; sign-in only adds persistence (saved history/language). The old `gated`
  // flag and every auth wall in the search paths were REMOVED — verify-search-is-free.ts fails the
  // build if any comes back.
  user: AuthUser | null;
  signIn: (u: AuthUser) => void;
  updateUser: (patch: Partial<AuthUser>) => void;
  signOut: () => void;
  // Permanently delete the account: delete the auth user on the SERVER, then wipe ALL on-device
  // state (history, parked message, saved language) from both memory AND storage. Distinct from
  // signOut, which keeps the saved history in storage so a later re-login restores it. (user
  // request: after deletion nothing from the old account must come back.)
  //
  // Resolves TRUE only when the server confirmed the deletion. On false NOTHING was destroyed and
  // the user is still signed in — the caller must surface the failure rather than claim success.
  deleteAccount: () => Promise<boolean>;
  searchCount: number;
  // A message the user typed but couldn't send because the gate fired. Persisted so it survives the
  // whole auth round-trip — including a full page reload during a real OAuth redirect — so after
  // sign-in the chat can replay it. The user never loses what they wrote or has to start over.
  pendingMessage: string | null;
  setPendingMessage: (m: string | null) => void;
  // CPC tracking (PRD §13): log a click-through whenever the user opens a partner listing.
  trackOpen: (listing: Listing) => void;
  // Resolve a listing by id from the live (Supabase-hydrated) catalog, so the in-app
  // browser opens real ingested listings — not just the bundled seed ids.
  findListing: (id: number) => Promise<Listing | undefined>;
  // Search history (PRD §13: retained until account deletion). Most-recent first.
  history: HistoryItem[];
  clearHistory: () => void;
  toggleStar: (id: string) => void;
  // Rename a sidebar entry. DISPLAY ONLY — it writes `title`/`titleSource`/`titleUpdatedAt` and
  // touches nothing else on the entry: not the query, the snapshot, the id, the star, or `ts`.
  // An empty/blank name clears the manual title and hands the row back to auto-titling.
  renameHistory: (id: string, title: string) => void;
  // Press-hold-drag reorder: place `id` between prevId (above) and nextId (below). POSITION ONLY —
  // the pure contract (no duplicate, no loss, no field but `order` touched) lives in
  // src/lib/sidebarReorder.ts and is executed by scripts/verify-sidebar-reorder.ts.
  reorderHistory: (id: string, prevId: string | null, nextId: string | null) => void;
  // Drag-to-Favorites (owner 2026-08-25): set starred AND land the row at the top of its new
  // bucket in one write — the ⋯ menu's toggleStar stays the tap path, this is the drag path.
  starHistory: (id: string, starred: boolean) => void;
  deleteHistory: (id: string) => void;
  // Record a free-text user message as the active chat's sidebar entry. First message → creates a
  // new chat in Recent with the user's text as the title; subsequent messages → update the same
  // chat's title to the LATEST user text and bump it to the top. Signed-in users only — a guest's
  // chat-only conversations are session-only. Returns the chat id used. (user request.)
  recordChatTurn: (text: string) => string | null;
  // Which history chat is currently open, so the sidebar can highlight it (light green) and the user
  // always knows which conversation they're in. `null` on Home / New Chat (no chat selected).
  // TRUE once the initial Supabase session restore has settled. Anything that renders for
  // SIGNED-OUT users must gate on this as well as `user`: during restore `user` is null, so a
  // `!user` test alone briefly reads a logged-in visitor as logged out (the flash GoogleOneTap
  // documents at its own gate). Already in this provider's memo deps — only the surface is new.
  authChecked: boolean;
  activeChatId: string | null;
  setActiveChat: (id: string | null) => void;
  // Support / About Us are shown as in-app popups (centered dialog over a dimmed page) rather than
  // full-screen routes, so they open from the drawer without navigating away.
  modal: 'support' | 'about' | null;
  openModal: (m: 'support' | 'about') => void;
  closeModal: () => void;
  // Sign-in popup (owner 2026-08-15): a true in-place overlay, same pattern as modal/openModal/
  // closeModal above — never a route, so the screen underneath (the Filter page, wherever the user
  // actually is) is never navigated away from or unmounted. See src/components/AuthModal.tsx.
  authOpen: boolean;
  openAuth: () => void;
  closeAuth: () => void;
  // Read-only exposure for the popup's auto-show gate (shouldAutoShowAuthPopup, owner 2026-08-28):
  // null = the hasSeenIntro flag is still being read, false = the intro is pending/playing, true =
  // done. The popup may only auto-raise on `true`, so it never covers the intro film.
  introSeen: boolean | null;
  // The small sign-in card's in-memory dismissal (owner 2026-08-29): true once this load's
  // visitor sent something (Filter search / Agent message) or closed the card. Never persisted —
  // a refresh brings the card back; an auth transition resets it (epoch effect above).
  signInCardDismissed: boolean;
  dismissSignInCard: () => void;
  // First-run cinematic intro (the eagle clip). Shows ONCE, only for a brand-new logged-out
  // visitor; persisted via a `hasSeenIntro` flag so it never replays. `showIntro` waits until both
  // the saved flag is read AND the auth session is resolved, so it never flashes for a returning
  // signed-in user. `dismissIntro` is called when the video finishes (or fails, as a safety).
  showIntro: boolean;
  dismissIntro: () => void;
};

const Ctx = createContext<AppState | null>(null);

// When true, the intro replays on every logged-out load (and the "seen" flag isn't persisted) so it
// can be re-watched while previewing. Production behaviour is false → shows once, first run only.
const INTRO_DEMO_MODE = false;

// History is stored PER ACCOUNT, keyed by the user's identity (phone/email), NOT under one shared
// key. A single global 'history' key leaked across sessions: logging into a different account — or
// back in after a delete — would resurrect the previous searches. Scoping by `sub` keeps each
// account's chats isolated, so a fresh login starts clean and a deleted account stays deleted.
const historyKey = (sub: string) => 'history:' + sub;

// What of `history` goes to LOCAL disk. Transcripts are the heavyweight part (revealed cards ×
// turns), so localStorage keeps them only on the LOCAL_TRANSCRIPT_ENTRIES most recently active
// chats — the same bounded-cache pattern as snapshots. The server keeps every transcript;
// hydrateTranscript() refetches a pruned one when its chat is opened. Pruning happens ONLY at the
// serialization boundary — in-memory state keeps every transcript, so switching between chats in
// one session never loses anything regardless of age.
const serializeHistoryForDisk = (items: HistoryItem[]): string => {
  const byActivity = items.slice().sort((a, b) => (b.tRev ?? b.ts) - (a.tRev ?? a.ts));
  const keep = new Set(byActivity.filter((it) => it.transcript).slice(0, LOCAL_TRANSCRIPT_ENTRIES).map((it) => it.id));
  return JSON.stringify(items.map((it) => (it.transcript && !keep.has(it.id) ? { ...it, transcript: undefined } : it)));
};

// The sidebar-list envelope pushed to the server (`user_chats.meta`): the HistoryItem minus its two
// heavyweight local-cache fields. The transcript has its own column; snapshots are strictly a local
// instant-open cache and would only bloat every metas load.
const chatMetaOf = (it: HistoryItem): ChatMeta => {
  // `txStale` is a DEVICE-LOCAL verdict ("my cached transcript is older than the server's activity")
  // and must never travel: pushed up and merged back down it would mark a perfectly fresh transcript
  // stale on every device, forcing endless refetches and, worse, outliving the condition it records.
  const { snapshot: _s, transcript: _t, txStale: _x, ...meta } = it as HistoryItem & { txStale?: boolean };
  return meta as ChatMeta;
};

// Erase storage keys SYNCHRONOUSLY on web. AsyncStorage's own removal resolves a tick later, and
// both sign-out and delete-account are followed by a navigation ~1.2s later (settings.tsx) — a
// reload landing in that gap used to re-hydrate history the user had just deleted. This mirrors the
// synchronous WRITES in toggleStar/deleteHistory, which exist for the identical reason. Native has
// no localStorage; there the AsyncStorage call beside each caller is the erase. (owner 2026-08-17.)
const removeKeysSync = (keys: string[]) => {
  try {
    if (typeof localStorage === 'undefined') return;
    for (const k of keys) localStorage.removeItem(k);
  } catch {}
};
// The old shared key. We proactively purge it so its stale, cross-account contents never reappear.
const LEGACY_HISTORY_KEY = 'history';

export function AppProvider({ children }: { children: ReactNode }) {
  // The FILTER (home) defaults to Buy highlighted (user request). emptyQuery() stays Rent-default for
  // the agent/chat base — this override is only the filter form's starting state. Single source of
  // truth with src/app/index.tsx's Clear All reset target (src/lib/searchDefaults.ts) — was a second,
  // independent inline copy of the same literal before 2026-07-13.
  const [query, setQueryState] = useState<SearchQuery>(HOME_DEFAULT_QUERY());
  // Ezhalah is a pure aggregator showing only REAL scraped listings. There's no whole-table load
  // anymore — each search fetches its own matching subset from Supabase (see runQuery →
  // fetchListingsForQuery). dataSource is constant 'supabase' (kept for any UI that reads it).
  const dataSource: DataSource = 'supabase';
  const [user, setUser] = useState<AuthUser | null>(null);
  // OBSERVABILITY (owner 2026-08-26): give every crash report the pseudonymous `sub` so a wave of
  // errors from one user groups correctly for triage. `sub` is the email/e164 identifier the app
  // already uses everywhere internally — never phone/email/name (observability.ts's scrubEvent
  // enforces the field allowlist independently, so a future field addition here can not leak PII).
  useEffect(() => { identifyUser(user?.sub ?? null); }, [user]);
  const [searchCount, setSearchCount] = useState(0);
  // Keep the user's name bilingual: when we only know one script (e.g. Google gives a Latin name),
  // generate the other once in the background so the Arabic UI can show the Arabic spelling without
  // waiting for the user to edit. Runs at most once per distinct name. (see lib/nameSync.)
  const nameSyncRef = useRef('');
  const [history, setHistory] = useState<HistoryItem[]>([]);
  // Mirror for async readers (hydrateTranscript, the sync push) — setState closures go stale.
  const historyRef = useRef<HistoryItem[]>([]);
  useEffect(() => { historyRef.current = history; }, [history]);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const [modal, setModal] = useState<'support' | 'about' | null>(null);
  const [authOpen, setAuthOpen] = useState(false);
  const [pendingMessage, setPendingMessageState] = useState<string | null>(null);
  // `null` while the saved flag is still being read from storage; the intro stays hidden until then.
  const [introSeen, setIntroSeen] = useState<boolean | null>(null);
  // True once we know the auth state (session restored or confirmed absent), so the intro decision
  // doesn't race the Supabase session lookup and flash for a returning signed-in user.
  const [authChecked, setAuthChecked] = useState(false);
  // AUTH-GATED APPEARANCE (owner 2026-08-28): mirror auth into the theme system once it is KNOWN.
  // Adoption enables the stored preference; a COMPLETED signed-in→signed-out transition (incl.
  // external revocation observed via onAuthStateChange) resets to Light and clears the stored
  // preference. Boot-as-guest is NOT a transition — nothing to clear, the gate already gives Light.
  const themeWasSignedInRef = useRef(false);
  useEffect(() => {
    if (!authChecked) return;
    const is = !!user;
    if (is) setThemeAuthState(true);
    else if (themeWasSignedInRef.current) resetThemeForSignOut();
    else setThemeAuthState(false);
    themeWasSignedInRef.current = is;
  }, [authChecked, user]);

  // THE SMALL SIGN-IN CARD's dismissal (owner 2026-08-29): IN-MEMORY ONLY, deliberately never
  // persisted — «it goes away once the user sends something» and comes back «when the user
  // refresh». Set by the two send sites (Filter onSearch, Agent send — voice funnels into it) and
  // by the card's own X; reset by construction on any fresh load.
  const [signInCardDismissed, setSignInCardDismissed] = useState(false);

  // AUTH EPOCH (owner 2026-08-29, #1214): a dismissal lives exactly as long as one continuous
  // signed-in-or-out stretch. This effect is the ONE writer that ends an epoch: on every change of
  // the signed-in boolean — sign-in, sign-out, account deletion, or a session dying in
  // onAuthStateChange — the stale dismissal is cleared, so the next logged-out state is the
  // canonical one (card eligible) instead of inheriting a flag stamped in a previous auth life.
  // `null` start skips the mount pass: state is fresh on mount anyway.
  const prevSignedInRef = useRef<boolean | null>(null);
  useEffect(() => {
    const now = !!user;
    const prev = prevSignedInRef.current;
    prevSignedInRef.current = now;
    if (prev === null || dismissalOutlivesTransition(prev, now)) return;
    setSignInCardDismissed(false);
  }, [user]);

  // Backfill the missing-script spelling of the user's name (once per name) so both stay synced.
  useEffect(() => {
    const nm = user?.name?.trim();
    if (!nm || (user?.nameEn && user?.nameAr)) return;
    if (nameSyncRef.current === nm) return;
    nameSyncRef.current = nm;
    let cancelled = false;
    buildSyncedName(nm).then((synced) => {
      if (!cancelled) setUser((u) => (u && u.name === synced.name ? { ...u, ...synced } : u));
    });
    return () => { cancelled = true; };
  }, [user?.name, user?.nameEn, user?.nameAr]);

  // Language persistence is auth-gated. A SIGNED-IN user keeps their chosen/detected language across a
  // refresh. A GUEST is ALWAYS Arabic-first on a fresh load — typing an English letter in the filter,
  // or sending an English message to the agent, flips the UI live for that session, but a refresh /
  // leaving resets to the Arabic default (nothing is saved). On WEB the signed-in language is applied
  // synchronously at first paint (i18n readSavedLocale, no flash); the effects below cover NATIVE and
  // enforce the guest reset. (user request.)
  const { locale, setLocale } = useI18n();
  const localeInitRef = useRef(false);
  // WHICH account's history is currently loaded — not merely "did we load once". A boolean here was
  // a real bug: the hydrate effect is one-shot, so a user who signed in DURING a session (the guard
  // already having run while they were a guest) never had their own saved history read, and the
  // sidebar stayed empty until a full reload. Holding the key makes the effect re-run whenever the
  // account changes, which is the only correct trigger. null = nothing loaded yet.
  const historyLoadedRef = useRef<string | null>(null);

  // React to auth state: signed-in → enable persistence + restore the saved language once; guest →
  // disable persistence, clear any saved value, and snap back to the Arabic default for this load.
  useEffect(() => {
    if (!authChecked) return;
    if (user) {
      setLocalePersistence(true);
      if (!localeInitRef.current) {
        localeInitRef.current = true;
        AsyncStorage.getItem(LOCALE_KEY)
          .then((v) => { if (v === 'en' || v === 'ar') setLocale(v as Locale); })
          .catch(() => {});
      }
    } else {
      setLocalePersistence(false); // guest → never remember the language
      localeInitRef.current = false;
      AsyncStorage.removeItem(LOCALE_KEY).catch(() => {});
      // Fresh guest load (or just logged out): start in Arabic. This runs only when auth state changes,
      // not on every locale change, so a guest's in-session switch to English is left untouched.
      if (getLocale() !== 'ar') setLocale('ar');
    }
  }, [authChecked, user, setLocale]);

  // Persist the active language ONLY for a signed-in user (native; web persists synchronously via the
  // auth-gated persistLocale in setLocale). A guest never writes their language.
  useEffect(() => {
    if (!user) return;
    AsyncStorage.setItem(LOCALE_KEY, locale).catch(() => {});
  }, [locale, user]);

  // Restore saved chats. SIGNED-IN only — see the persistence effect below for why a guest's
  // searches are never written to disk (owner decision 2026-08-20: anonymous = temporary).
  //
  // Re-runs when the ACCOUNT changes, not once per mount. Guest → sign-in must pull that user's own
  // saved history into the sidebar immediately; signing into a different account must replace it,
  // never merge. Keyed on the storage key so both transitions are the same code path.
  useEffect(() => {
    if (!authChecked) return;
    const key = user ? historyKey(user.sub) : null;
    if (historyLoadedRef.current === (key ?? 'guest')) return;
    historyLoadedRef.current = key ?? 'guest';
    // Purge the legacy shared key once — it's the source of the cross-account leak. From here on,
    // history lives only under this account's own key.
    AsyncStorage.removeItem(LEGACY_HISTORY_KEY).catch(() => {});
    // Guests: nothing on disk to read, and anything a previous build left behind is removed rather
    // than adopted, so an anonymous search can never resurface after a refresh.
    if (!key) {
      removeKeysSync([historyKey('guest')]);
      AsyncStorage.removeItem(historyKey('guest')).catch(() => {});
      setHistory([]);
      return;
    }
    // Signing in from a guest session must not carry the guest's in-memory chats into the account —
    // start from what this account itself has saved, nothing more.
    setHistory([]);
    AsyncStorage.getItem(key)
      .then((v) => {
        if (!v) return;
        // A later account switch could have landed while this read was in flight; only apply it if
        // this is still the account we are showing.
        if (historyLoadedRef.current !== key) return;
        try {
          const saved = JSON.parse(v);
          // Normalize every entry's query at this ONE hydration boundary: an entry written by an
          // older build may lack fields added since (a missing priceInput crashed filterToChat when
          // the chat was reopened from the sidebar — 2026-08-23) or carry the legacy typeGroup
          // scalar. migrateGroups fills only the required strings whose absence crashes — it never
          // invents a value that would change what the replayed search does.
          if (Array.isArray(saved)) {
            setHistory((saved as HistoryItem[]).map((h) => ({ ...h, query: migrateGroups({ ...h.query }) })));
          }
        } catch {}
      })
      .catch(() => {});
  }, [authChecked, user]);

  // Persist chats — SIGNED-IN USERS ONLY, under their own key.
  //
  // ACCOUNT-AWARE BY OWNER DECISION (2026-08-20): "Logged out → refresh = current temporary search
  // disappears. Logged in → previous completed search is saved and recoverable from sidebar
  // history." A guest's searches therefore live in memory for the session and are never written to
  // disk, so a refresh cannot bring them back. This costs nothing visible: the sidebar's history
  // list is rendered only for a signed-in user, so the old `history:guest` bucket was invisible
  // retention of anonymous searches — exactly what the owner ruled against.
  //
  // Writes localStorage DIRECTLY (synchronous) on web so a refresh immediately after a star/delete can
  // never lose the change. AsyncStorage on native handles the same job. (user-reported persistence bug.)
  useEffect(() => {
    if (!historyLoadedRef.current) return;
    if (!user) return;                       // guests: session-only, nothing on disk
    const key = historyKey(user.sub);
    const json = serializeHistoryForDisk(history);
    try {
      if (typeof localStorage !== 'undefined') localStorage.setItem(key, json);
    } catch {}
    AsyncStorage.setItem(key, json).catch(() => {});
  }, [history, user]);

  // ── SERVER SYNC (owner 2026-08-25 — conversations survive a new browser and logging back in) ──
  // Pull: after the local restore for a signed-in account, fetch the server's chat metas and merge
  // by id — the newer side (per-entry activity stamp) wins; server-only chats appear, local-only
  // chats stay and get pushed. Transcripts are NOT pulled here (metas stay small) — hydrateTranscript
  // fetches one lazily when its chat is opened.
  const serverMergedRef = useRef<string | null>(null);
  useEffect(() => {
    if (!authChecked || !user || !supabase) return;
    const key = historyKey(user.sub);
    if (serverMergedRef.current === key) return;
    serverMergedRef.current = key;
    loadChatMetas().then((rows) => {
      if (!rows || serverMergedRef.current !== key) return;
      setHistory((h) => {
        const byId = new Map(h.map((it) => [it.id, it] as const));
        for (const r of rows) {
          const meta = { ...r.meta, id: r.id } as unknown as HistoryItem;
          if (typeof meta.ts !== 'number' || !meta.query) continue; // malformed row: ignore, never crash the list
          // Precedence lives in src/lib/chatMerge.ts so this and hydrateTranscript cannot drift.
          // When the server reports newer activity the local transcript is carried over but MARKED
          // STALE — rendering it would show a shorter conversation and the capture effect would then
          // push that truncated view over the server's newer copy (silent, permanent history loss).
          byId.set(r.id, mergeOne(byId.get(r.id) as never, meta as never) as unknown as HistoryItem);
          // local newer → mergeOne keeps local whole; the push effect below writes it up.
        }
        return [...byId.values()].sort((a, b) => (b.order ?? b.ts) - (a.order ?? a.ts)).slice(0, 50);
      });
      // Baseline AFTER the merge lands so the first push diff is against what the server now holds.
      syncBaselineRef.current = new Map(rows.map((r) => {
        const m = r.meta as unknown as HistoryItem;
        return [r.id, Math.max(m.ts ?? 0, m.tRev ?? 0)];
      }));
      syncReadyRef.current = key;
    }).catch(() => { /* offline → local-only session; next sign-in retries */ });
  }, [authChecked, user]);

  // Push: debounced write-through. Diffs against the last known server state (per-entry activity
  // stamp) and upserts only changed chats — meta always, transcript only when this device holds one
  // whose tRev moved (never nulling a server transcript a pruned local cache no longer has).
  // Deletions propagate ONLY for ids the server was known to hold (the baseline), so a not-yet-
  // merged local list can never mass-delete the account's server history. Fire-and-forget with the
  // baseline updated per row on success; a failed write simply retries on the next change.
  const syncBaselineRef = useRef<Map<string, number>>(new Map());
  const syncReadyRef = useRef<string | null>(null);
  const syncTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    if (!user || !supabase) return;
    if (syncReadyRef.current !== historyKey(user.sub)) return; // push only after the pull merged
    if (syncTimerRef.current) clearTimeout(syncTimerRef.current);
    syncTimerRef.current = setTimeout(() => {
      const items = historyRef.current;
      const base = syncBaselineRef.current;
      const seen = new Set<string>();
      for (const it of items) {
        seen.add(it.id);
        const stamp = Math.max(it.ts, it.tRev ?? 0);
        if ((base.get(it.id) ?? -1) >= stamp) continue;
        void upsertChat(it.id, chatMetaOf(it), it.transcript).then((ok) => { if (ok) base.set(it.id, stamp); });
      }
      const gone = [...base.keys()].filter((id) => !seen.has(id));
      if (gone.length) void deleteChats(gone).then((ok) => { if (ok) for (const id of gone) base.delete(id); });
    }, 1200);
    return () => { if (syncTimerRef.current) clearTimeout(syncTimerRef.current); };
  }, [history, user]);

  // Read the one-time "already saw the intro" flag on launch. In demo mode we ignore any stored flag
  // so the intro shows on every fresh load (and can be re-watched by refreshing).
  useEffect(() => {
    if (INTRO_DEMO_MODE) {
      setIntroSeen(false);
      return;
    }
    AsyncStorage.getItem('hasSeenIntro')
      .then((v) => setIntroSeen(v === '1'))
      .catch(() => setIntroSeen(false));
  }, []);

  // Restore a message that was parked at the gate before a previous sign-in attempt, so it survives
  // an OAuth page reload. The chat consumes and clears it once the user is signed back in.
  useEffect(() => {
    AsyncStorage.getItem('pendingMessage')
      .then((v) => { if (v) setPendingMessageState(v); })
      .catch(() => {});
  }, []);

  // Record a search into history. De-dupe by the QUERY itself (deal/location/category/type/detail/
  // price) rather than the label text — so the same search recorded again, even after the UI language
  // flipped (which changes the label string), updates the one existing chat instead of spawning a
  // duplicate. The freshly-recorded chat becomes the active one (highlighted in the sidebar).
  // Identity lives in src/lib/savedSearchIdentity.ts — read the header there for why. In short: this
  // used to hand-list 17 of SearchQuery's 41 fields, so two searches differing ONLY in سنوي/شهري/
  // كلاهما, in إيجار+شراء, or in ANY Advanced Filter answer were treated as the same chat; the newer
  // one overwrote the older entry and that search disappeared from the sidebar (15/15 measured).
  // Comparing everything-but-a-justified-ignore-list also means the next field added to SearchQuery
  // is included automatically instead of silently reopening the hole.
  const sameQuery = isSameSavedSearch;
  // If the user already has a chat for this query, KEEP it (its id and its starred flag) — just
  // refresh the label/timestamp and bump it to the top. Without this, re-running the same search was
  // creating a brand-new entry and silently nuking the star. (user-reported bug.)
  // Snapshot bounds: SNAPSHOT_CAP cards per entry, snapshots kept on the SNAPSHOT_ENTRIES most
  // recent entries only — keeps the persisted history well under localStorage limits while the
  // chats a user actually reopens (recent ones) stay instant. Older entries fall back to the live
  // replay path, unchanged.
  const SNAPSHOT_CAP = 20;
  const SNAPSHOT_ENTRIES = 15;
  const recordHistory = (q: SearchQuery, result?: SearchResult, chatId?: string | null) => {
    const label = queryLabel(q);
    // Truncated snapshot restarts paging at 0 with hasMore — loadMore de-dups against the held
    // cards, so the continuation is gap-free; an untruncated one keeps its exact paging state.
    const snapshot: SearchResult | undefined = result
      ? result.listings.length > SNAPSHOT_CAP
        ? { ...result, listings: result.listings.slice(0, SNAPSHOT_CAP), pageOffset: 0, hasMore: true }
        : result
      : undefined;
    setHistory((h) => {
      // CONVERSATION IDENTITY (owner 2026-08-25 — «treat Ezhalah's chat like ChatGPT»). A chat is
      // the CONVERSATION, not the query. A continuation turn (AF round, refine chip, follow-up)
      // names its chat and updates that one entry — its query becomes the latest narrowed state,
      // its transcript keeps every earlier round. Only with no chatId do we consider dedupe, and
      // then ONLY onto an entry with no held conversation: overwriting a chat that has a
      // transcript would destroy the very history this feature exists to keep, so a repeated
      // search starts its own new chat exactly like ChatGPT does.
      const prior = (chatId ? h.find((it) => it.id === chatId) : undefined)
        ?? (!chatId ? h.find((it) => !it.transcript && sameQuery(it.query, q)) : undefined);
      const id = prior?.id ?? chatId ?? 'h' + Date.now();
      const starred = prior?.starred ?? false;
      // TITLE (owner 2026-08-21). Auto-generate a concise summary, but a user-named row keeps its
      // name: canAutoRetitle() is the single place that rule lives, so re-running a renamed search
      // refreshes its results and timestamp WITHOUT reverting the title the user chose.
      const keepTitle = prior && !canAutoRetitle(prior);
      const title = keepTitle ? prior!.title : autoTitleForQuery(q, getLocale());
      const titleSource: TitleSource = keepTitle ? 'manual' : 'auto';
      const next: HistoryItem = {
        id, label, query: q, ts: Date.now(), starred,
        title, titleSource,
        ...(keepTitle && prior!.titleUpdatedAt ? { titleUpdatedAt: prior!.titleUpdatedAt } : {}),
        ...(snapshot ? { snapshot } : {}),
        // The conversation itself rides along on a continuation — agent.tsx re-captures it right
        // after the turn settles, but the entry must never lose what it already holds in between.
        ...(prior?.transcript ? { transcript: prior.transcript, tRev: prior.tRev } : {}),
      };
      setActiveChatId(id);
      const rest = h.filter((it) => it.id !== id);
      return [next, ...rest]
        .slice(0, 50)
        .map((it, i) => (i < SNAPSHOT_ENTRIES || !it.snapshot ? it : { ...it, snapshot: undefined }));
    });
  };

  // No startup catalog load anymore. Downloading the whole table (now 21k+ rows, ~47MB) timed out
  // and broke search. Each search fetches only its matching subset from Supabase via runQuery →
  // fetchListingsForQuery. (user-reported: app stuck on "Loading listings".)

  // Real auth: adopt an existing Supabase session on launch and keep `user` in sync
  // with the backend (covers OAuth redirects bouncing back to /auth and token refresh).
  useEffect(() => {
    if (!supabase) {
      setAuthChecked(true); // no backend → there is no session to wait for
      return;
    }
    let cancelled = false;
    supabase.auth.getSession().then(({ data }) => {
      const su = data.session?.user;
      if (!cancelled && su) {
        const method = (su.app_metadata?.provider as AuthUser['method']) ?? 'phone';
        setUser(mapSupabaseUser(su, method === 'google' || method === 'apple' ? method : 'phone'));
      }
      if (!cancelled) setAuthChecked(true);
    });
    const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => {
      const su = session?.user;
      if (su) {
        const method = (su.app_metadata?.provider as AuthUser['method']) ?? 'phone';
        setUser(mapSupabaseUser(su, method === 'google' || method === 'apple' ? method : 'phone'));
      } else {
        setUser(null);
      }
    });
    return () => sub.subscription.unsubscribe();
  }, []);

  const value = useMemo<AppState>(
    () => ({
      query,
      setQuery: (updater) => setQueryState((q) => updater(q)),
      resetQuery: () => setQueryState(emptyQuery()),
      // NEW CHAT — the single owner of "start clean" (owner permanent rule 2026-08-20: a saved chat
      // keeps its own state; New Chat never inherits anything from the previously active one).
      //
      // The bug this fixes: onNewChat only cleared the sidebar highlight and navigated home with a
      // `fresh` param, and Home's only reaction to `fresh` was replaying the hero ANIMATION. Nothing
      // reset the shared `query`, so the previous search's city, type, deal, period, price, beds and
      // every other Filter field rode straight into the new chat. The handler's own comment claimed
      // it reset state; the reset was never implemented.
      //
      // Resets to HOME_DEFAULT_QUERY (not emptyQuery): New Chat lands on the Filter home, whose true
      // default is Buy-highlighted, and that is also the store's own initial state — so a New Chat is
      // byte-identical to a cold app start, and to what «مسح الكل» already produces.
      //
      // Deliberately NOT touched: `history` (the saved chats must survive — that is the whole point)
      // and `user`. Results, result counts, pagination and every Advanced-Filter answer live in
      // agent.tsx's own component state, which is destroyed when New Chat navigates to '/', so they
      // need no clearing here — and must not be duplicated into the store just to be cleared.
      newChat: () => {
        setQueryState(HOME_DEFAULT_QUERY());
        setPendingMessageState(null);
        AsyncStorage.removeItem('pendingMessage').catch(() => {});
        setActiveChatId(null);
      },
      dataSource,
      user,
      searchCount,
      pendingMessage,
      setPendingMessage: (m) => {
        setPendingMessageState(m);
        if (m) AsyncStorage.setItem('pendingMessage', m).catch(() => {});
        else AsyncStorage.removeItem('pendingMessage').catch(() => {});
      },
      signIn: (u) => setUser(u),
      updateUser: (patch) => setUser((u) => (u ? { ...u, ...patch } : u)),
      signOut: () => {
        // Drop the session from MEMORY so the next guest never sees the previous user's chats: clear
        // history, search count, the open chat, and any parked message. This account's OWN saved
        // history (under its per-user key) is intentionally KEPT — a later re-login restores it
        // (restore flag reset so it can reload). The legacy shared key is purged so it can't leak.
        // Appearance resets FIRST and synchronously (same React batch as setUser) so the signed-out
        // UI lands already-Light — never a half-dark frame (owner 2026-08-28).
        resetThemeForSignOut();
        setUser(null);
        setHistory([]);
        setSearchCount(0);
        setActiveChatId(null);
        setPendingMessageState(null);
        // Also wipe the GUEST bucket, so the freshly-logged-out guest doesn't inherit the prior
        // signed-in user's in-memory chats getting re-written under 'history:guest'. (user request.)
        // Sync-first for the same reason as deleteAccount: settings.tsx navigates 1.2s after this,
        // and an async-only removal can lose that race.
        removeKeysSync(['pendingMessage', LEGACY_HISTORY_KEY, historyKey('guest')]);
        AsyncStorage.multiRemove(['pendingMessage', LEGACY_HISTORY_KEY, historyKey('guest')]).catch(() => {});
        historyLoadedRef.current = null;
        void signOutBackend();
      },
      deleteAccount: async () => {
        // SERVER FIRST, and nothing is destroyed until it confirms. If the delete fails the account
        // still exists, so wiping the device would throw away the user's history for nothing and
        // still leave the account signed-in-able. On failure this returns false having changed
        // NOTHING, and settings.tsx shows the error instead of claiming success.
        const serverDeleted = await deleteAccountBackend();
        if (!serverDeleted) return false;
        // Permanent: wipe everything tied to THIS account from storage AND memory, then sign out.
        // After this, signing in again — even with the same provider — starts truly fresh: none of
        // the old history, parked message, or saved language comes back. (user request: deleted
        // account must not resurrect its data.)
        //
        // The guest bucket goes too: this is a "delete everything of mine on this device" action, and
        // signOut already clears it — leaving it only here would strand the chats made before signup.
        const keys = ['pendingMessage', 'locale', LEGACY_HISTORY_KEY, historyKey('guest')];
        if (user) keys.push(historyKey(user.sub));
        // SYNCHRONOUS on web, for exactly the reason toggleStar/deleteHistory below write
        // synchronously: AsyncStorage resolves on a later tick, and settings.tsx navigates ~1.2s
        // after calling this. A reload landing in that window re-hydrated the very history this is
        // supposed to erase — the user-reported "I deleted my account and the chats are still
        // there". localStorage.removeItem is sync, so the erase has already happened by the time
        // this function returns. (owner report 2026-08-17.)
        removeKeysSync(keys);
        AsyncStorage.multiRemove(keys).catch(() => {});
        // Appearance: the deletion COMPLETED (server confirmed above — never on dialog-open, never
        // on إلغاء, never on a failed delete): back to Light, stored preference cleared. (owner
        // 2026-08-28)
        resetThemeForSignOut();
        setUser(null);
        setHistory([]);
        setSearchCount(0);
        setActiveChatId(null);
        setPendingMessageState(null);
        historyLoadedRef.current = null;
        // No signOutBackend() here — deleteAccountBackend() above already signed out, and only after
        // the auth user was actually deleted.
        return true;
      },
      // `record` defaults to true: a genuine new search adds a history chat. Reopening a saved chat
      // passes record=false so just VIEWING it never spawns a fresh entry — a new chat is only made
      // by a new filter search / chat message (or New Chat), keeping the list clean. (user request.)
      runQuery: async (q, record = true, signal, chatId) => {
        // A Room is always exactly 1 bedroom — normalize here so every path (filter or AI agent)
        // shows "1 bedroom" and uses the room price ladder, no matter what detail came in. (user request.)
        if (q.type === 'Room') q = { ...q, detail: '1' };
        // ONE LOCATION ENGINE (user: same resolution everywhere). The FILTER path resolves location up
        // front and attaches q.locationMatch. The AI-CHAT path does NOT — Gemini returns a raw city
        // string that may be a typo or homophone ("Rakk"→Al Rakah, "القرص"→Ar Rass), which dead-ended
        // at "no results". Resolve it HERE, through the SAME resolver the filter uses, so a near miss
        // still finds the real city and the Search Summary shows the corrected Region → City → District.
        if (!q.locationMatch && q.location && q.location.trim()) {
          try {
            await ensureLocationIndex();
            const lm = resolveLocation(q.location, getLocale());
            if (lm.kind !== 'none') {
              const display =
                lm.kind === 'district' || lm.kind === 'city' || lm.kind === 'region' ? lm.label : (lm.city || q.location);
              let districts = q.districts;
              if (lm.kind === 'district') {
                districts = lm.districts.length ? lm.districts : (lm.label ? [lm.label] : districts);
              } else if (lm.kind === 'area' || lm.kind === 'landmark' || lm.kind === 'geography' || lm.kind === 'lifestyle') {
                const clean = lm.districts.filter(Boolean);
                if (clean.length) districts = clean;
              }
              q = { ...q, location: display, locationMatch: lm, districts };
            }
          } catch { /* fall back to the raw location — never hard-fail the search */ }
        }
        // Fetch ONLY this query's matching subset from Supabase (city + type + deal pushed server-side),
        // then run the full client engine on it. Replaces the old "load the whole table" approach that
        // timed out at 21k+ rows. null = backend error (flag it so the UI shows retry, not "no matches").
        // pageCandidates/pageTotal come back straight off this call's own result (no shared module state
        // that a concurrent fetchListingsForQuery() call could clobber before we read it — 2026-08-03 fix).
        const { listings: rows, pageCandidates: pageCand, pageTotal } = await fetchListingsForQuery(q, { signal });
        // Repeat-visit rotation offset: a per-filter counter persisted in localStorage so returning to the
        // SAME filter (deal + location/districts) later surfaces a DIFFERENT high-quality first 25, never the
        // exact same set — while staying strictly inside the filters. Device-local (guests included);
        // best-effort (no localStorage → offset 0, no rotation). (user 2026-06-27.)
        let visitOffset = 0;
        try {
          const sig = `ezh_rot:${q.deal}|${q.regionPin ?? ''}|${(q.districts ?? []).join(',')}|${(q.location ?? '').trim()}`;
          const ls = (globalThis as { localStorage?: { getItem(k: string): string | null; setItem(k: string, v: string): void } }).localStorage;
          const prev = parseInt(ls?.getItem(sig) ?? '0', 10);
          visitOffset = Number.isFinite(prev) ? prev : 0;
          ls?.setItem(sig, String(visitOffset + 1));
        } catch { /* no localStorage (SSR/native) → no rotation, fine */ }
        const r = runSearch(q, buildPools(rows ?? []), { fetchFailed: rows === null, visitOffset });
        // Attach the RESOLVED query so the caller renders the Search Summary from what actually ran
        // (the corrected city/region), not the raw pre-resolution text. (one-engine summary parity.)
        const result: SearchResult = { ...r, query: q, pageOffset: pageCand, hasMore: pageCand >= 1500, matchTotal: pageTotal };
        // STOP-BUTTON GUARD (owner 2026-08-18): "A cancelled request must never later write results
        // into the UI or history." fetchListingsForQuery already aborts the underlying network calls
        // on `signal`, but a response can still be mid-flight (or already back) at the exact instant
        // Stop is pressed — this check is what makes the no-write guarantee absolute regardless of
        // that race, not just "usually true because the network call also got cancelled". Checked
        // AFTER the await (signal.aborted only ever flips true, never back to false), so a Stop that
        // lands one tick after this line simply loses the race and the write already happened —
        // exactly the same instant a real completed search would have been too late to cancel.
        if (record && !signal?.aborted) {
          setSearchCount((c) => c + 1);
          // Record the chat in memory (it shows in the current session). Persistence only happens for
          // signed-in users — a guest's chats are never written to storage, so they vanish on leave.
          // The result rides along so reopening this chat renders instantly (no re-search).
          recordHistory(q, result, chatId);
        }
        return result;
      },
      // FULL-CONVERSATION CAPTURE (owner 2026-08-25). agent.tsx serializes the settled conversation
      // and hands it here; the entry keeps it (memory for every chat, disk for the most recent
      // LOCAL_TRANSCRIPT_ENTRIES, server for all — see the persistence + sync effects). `ts` is
      // deliberately NOT bumped: revealing more cards or a receipt landing is not a new search, and
      // resorting the sidebar on it would surprise; `tRev` alone tells sync the transcript moved.
      saveTranscript: (id, transcript) => {
        // DIRECT disk write FIRST, from the ref — setState updaters are not guaranteed to run
        // during a page unload, and the flush-on-exit path (agent.tsx pagehide) depends on this
        // landing synchronously. The setHistory below is the same write into React state; both are
        // idempotent, and the in-state updater's own disk write simply repeats this one.
        const tRev = Date.now();
        if (user) try {
          const cur = historyRef.current;
          const idx0 = cur.findIndex((it) => it.id === id);
          if (idx0 >= 0 && typeof localStorage !== 'undefined') {
            const direct = cur.slice();
            direct[idx0] = { ...cur[idx0], transcript, tRev };
            localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(direct));
          }
        } catch {}
        setHistory((h) => {
          const idx = h.findIndex((it) => it.id === id);
          if (idx < 0) return h;
          const next = h.slice();
          // UNION of two concurrent changes: upstream's single pre-minted `tRev` (shared by the
          // flush-on-exit disk write and this state update, so both stamp the SAME revision) and
          // withFreshTranscript, which additionally CLEARS txStale — a freshly captured transcript
          // is by definition not the stale copy the server-merge warned about.
          next[idx] = withFreshTranscript(h[idx] as never, transcript, tRev) as unknown as HistoryItem;
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        });
      },
      // Transcript pruned locally (older than LOCAL_TRANSCRIPT_ENTRIES) or absent on this device —
      // pull the server's copy, validate it, attach it. Returns null when the server has none
      // either (legacy chat) so the caller can fall back to the snapshot/replay path.
      hydrateTranscript: async (id) => {
        const entry = historyRef.current.find((it) => it.id === id);
        // A trusted local copy renders instantly. A copy the merge marked STALE must lose to the
        // server's newer one — but if the server has none (legacy chat / offline), the local copy is
        // still the user's conversation and is kept rather than showing them a blank chat.
        const t = await pickTranscript<PersistedChat>(
          entry?.transcript,
          !!(entry as { txStale?: boolean } | undefined)?.txStale,
          async () => {
            if (!user) return null;
            const fetched = await fetchChatTranscript(id);
            const valid = fetched ? restoreChat(fetched) : null;
            if (!valid) return null;
            return { v: 1, msgs: valid.msgs, revealCount: valid.revealCount, afReceipt: valid.afReceipt, guidedPills: valid.guidedPills };
          },
        );
        if (!t) return null;
        if (t !== entry?.transcript || (entry as { txStale?: boolean } | undefined)?.txStale)
          setHistory((h) => h.map((it) => (it.id === id ? withFreshTranscript(it as never, t, it.tRev ?? Date.now()) as unknown as HistoryItem : it)));
        return t;
      },
      // Load More (owner 2026-07-08): fetch the NEXT real page of matching listings beyond `offset`
      // (filter-first, recency order) so broad searches page through the FULL set. Returns the ranked
      // page + the advanced cursor; the caller appends (de-duped) to the shown list.
      loadMoreListings: async (q: SearchQuery, offset: number) => {
        const PAGE_MORE = 500;
        const { listings: rows, pageCandidates: cand } = await fetchListingsForQuery(q, { offset, limit: PAGE_MORE });
        const r = runSearch(q, buildPools(rows ?? []));
        return { listings: r.listings, nextOffset: offset + cand, hasMore: cand >= PAGE_MORE };
      },
      trackOpen: (listing) => {
        void trackClick(listing, user?.sub ?? null);
      },
      findListing: async (id) => {
        // Try the session cache (every searched/opened listing is cached), else fetch the single row.
        const cached = getCachedListing(id);
        if (cached) return cached;
        return (await fetchListingById(id)) ?? undefined;
      },
      history,
      clearHistory: () => setHistory([]),
      // Toggle/delete write to storage SYNCHRONOUSLY in addition to the React effect — so a refresh
      // immediately after the click can't lose the change (the useEffect persist is async; localStorage
      // is sync). Functional setHistory + the computed next array keep state and storage in lock-step.
      // (user-reported bug: starring then refreshing was losing the star.)
      toggleStar: (id) =>
        setHistory((h) => {
          const next = h.map((it) => (it.id === id ? { ...it, starred: !it.starred } : it));
          // Signed-in only, same rule as the persistence effect: a guest has nothing on disk to keep
          // in step, and writing here would re-create the anonymous bucket the owner retired.
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        }),
      // RENAME = DISPLAY ONLY (owner rule 3, 2026-08-21). Spreading `it` and then assigning ONLY the
      // three title fields is what makes that structural rather than a promise: query, snapshot,
      // starred, id and `ts` are carried through untouched, so the conversation a renamed row opens
      // is byte-for-byte the search it always was. `ts` in particular must not move — it is "when
      // this search ran", and bumping it would silently reorder the sidebar on a rename.
      // Clearing the name (empty input) drops back to auto-titling rather than saving a blank row.
      renameHistory: (id, title) =>
        setHistory((h) => {
          const clean = (title ?? '').replace(/\s+/g, ' ').trim().slice(0, 120);
          const next = h.map((it) => {
            if (it.id !== id) return it;
            return clean
              ? { ...it, title: clean, titleSource: 'manual' as TitleSource, titleUpdatedAt: Date.now() }
              : { ...it, title: autoTitleForQuery(it.query, getLocale()), titleSource: 'auto' as TitleSource, titleUpdatedAt: Date.now() };
          });
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        }),
      // POSITION ONLY, by construction: applyMove maps a new `order` onto the moved row (or
      // renormalizes its bucket's orders) and carries every other field through untouched — it can
      // never rename, star, delete, duplicate, navigate, or touch the active chat. Same synchronous
      // localStorage write as toggleStar so a refresh right after the drop keeps the new order.
      reorderHistory: (id, prevId, nextId) =>
        setHistory((h) => {
          const next = applyMove(h, id, prevId, nextId);
          if (next === h) return h;
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        }),
      // Cross-bucket drop (drag-to-Favorites). applyStarMove is position+star ONLY by construction —
      // same ids, same length, every other field untouched. Same synchronous disk write as the
      // other row mutations so a refresh right after the drop keeps it.
      starHistory: (id, starred) =>
        setHistory((h) => {
          const next = applyStarMove(h, id, starred);
          if (next === h) return h;
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        }),
      deleteHistory: (id) =>
        setHistory((h) => {
          const next = h.filter((it) => it.id !== id);
          if (user) try {
            if (typeof localStorage !== 'undefined') localStorage.setItem(historyKey(user.sub), serializeHistoryForDisk(next));
          } catch {}
          return next;
        }),
      // Free-text chat → sidebar Recent entry. Signed-in only (guests don't get sidebar history for
      // chat-only messages). On the first user message of a chat, create a new entry titled with
      // the user's exact text; subsequent messages in the same chat update the title to the LATEST
      // message and bump it to the top of Recent. (user request.)
      recordChatTurn: (text: string): string | null => {
        if (!user) return null;
        const v = (text ?? '').trim();
        if (!v) return null;
        const id = activeChatId ?? 'h' + Date.now();
        setHistory((h) => {
          const idx = h.findIndex((it) => it.id === id);
          let next: HistoryItem[];
          // A chat row is titled with a SHORT summary of what the user asked, not the whole
          // message (owner 2026-08-21: «ابي شقة بالرياض قريبة من المترو وتكون تحت 5000 بالشهر» →
          // «شقة بالرياض قرب المترو»). `label` keeps the raw text so nothing that reads the legacy
          // field loses information; only the displayed title is summarized.
          const auto = autoTitleForPrompt(v, getLocale());
          if (idx >= 0) {
            const prev = h[idx];
            const keep = !canAutoRetitle(prev);
            const updated: HistoryItem = {
              ...prev, label: v, ts: Date.now(),
              title: keep ? prev.title : auto,
              titleSource: keep ? 'manual' : 'auto',
              // New activity outranks an old manual slot (Note #9: most recent activity first).
              // Dropping `order` lets the fresh ts govern, exactly like recordHistory's new object.
              order: undefined,
            };
            next = [updated, ...h.filter((it) => it.id !== id)];
          } else {
            const entry: HistoryItem = { id, label: v, query: emptyQuery(), ts: Date.now(), title: auto, titleSource: 'auto' };
            next = [entry, ...h].slice(0, 50);
          }
          try {
            const k = historyKey(user.sub);
            if (typeof localStorage !== 'undefined') localStorage.setItem(k, serializeHistoryForDisk(next));
          } catch {}
          return next;
        });
        if (activeChatId !== id) setActiveChatId(id);
        return id;
      },
      authChecked,
      activeChatId,
      setActiveChat: (id) => setActiveChatId(id),
      modal,
      openModal: (m) => setModal(m),
      closeModal: () => setModal(null),
      authOpen,
      openAuth: () => setAuthOpen(true),
      // Plain close again (2026-08-29): the centered modal no longer auto-raises, so a close
      // needs no memory — reopening is always an explicit control away.
      closeAuth: () => setAuthOpen(false),
      signInCardDismissed,
      dismissSignInCard: () => setSignInCardDismissed(true),
      introSeen,
      showIntro: introSeen === false && authChecked && !user,
      dismissIntro: () => {
        setIntroSeen(true); // session-only hide so it doesn't re-loop after the dissolve
        if (!INTRO_DEMO_MODE) AsyncStorage.setItem('hasSeenIntro', '1').catch(() => {});
      },
    }),
    [query, dataSource, user, searchCount, history, modal, authOpen, introSeen, signInCardDismissed, authChecked, pendingMessage, activeChatId, setActiveChatId],
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useApp(): AppState {
  const v = useContext(Ctx);
  if (!v) throw new Error('useApp must be used within AppProvider');
  return v;
}
