-- Mirror of live-only pg_cron jobs (cron-state drift sweep, 2026-08-15/16).
--
-- WHY: applying 20260815201404 (first-class parity-barrier schedule) aborted on its live-uniqueness
-- guard because job 'refresh-loc-rel-signals' (jobid 22) covered minute :49 while existing in NO
-- file under supabase/migrations/. A full sweep of live cron.job vs the repo then found THIRTY live
-- jobs whose creation (jobname + schedule + command) is recorded nowhere in git — mostly jobids
-- 1-35 from before the mirror discipline started (~2026-07-16), plus five from 2026-08 sessions
-- (jobids 60, 61, 63, 65, 66). The migration-drift guard cannot see this class of drift: it
-- compares supabase_migrations.schema_migrations versions, not cron.job rows.
--
-- WHAT THIS DOES: records the exact live state (captured 2026-08-15, generated by Postgres itself
-- via format('%L') from cron.job — not hand-typed) and re-asserts it defensively:
--   * job absent            -> cron.schedule() it (and re-apply active=false where recorded);
--   * job present+identical -> no-op;
--   * job present+DIFFERENT -> raise. Never blind-overwrite: cron.schedule() REPLACES the command
--     for an existing jobname, so an unconditional upsert here could undo a later legitimate
--     change. On mismatch, update this mirror to match live — not the other way round.
-- Applying this against today's production is a pure no-op verify (all 30 exist; equality is
-- byte-checked), which also proves the transcription below is exact.
--
-- NOT in scope (deliberate):
--   * No schedule/command is changed for any job — record-what-exists only, no re-staggering.
--   * 'gh-muktamel-weekly' (jobid 14) is recorded with active=false — it was deliberately paused
--     (20260714_pause_muktamel_cron.sql). This mirror must NEVER re-enable it.
--   * Jobs already created by a migration (e.g. normal-filter-barrier, mon-filter-parity-barrier)
--     are not repeated here, even where a later cron.alter_job re-staggered them off-record
--     (e.g. 20260810110905 moved jobids 33/42/43/50/53 by jobid); their creation is recoverable.
--   * Comment drift noted in passing: 20260810125629 says mon-pii-capture-sweep runs "every 20
--     minutes"; live is hourly at :36. The live schedule is what this file records.

do $mig$
declare
  r record;
  v_sched text; v_cmd text; v_active boolean;
  created int := 0;
begin
  for r in
    select * from (values
      ('refresh-listings', '30 2 * * *', '
  select net.http_post(
    url := ''https://aannarbkwcymrotzwdbo.supabase.co/functions/v1/ingest-listings'',
    headers := jsonb_build_object(
      ''Content-Type'', ''application/json'',
      ''apikey'', ''sb_publishable_vXzwxdpfrzmbwtbR5aXcKA_cMUO8hVB'',
      ''Authorization'', ''Bearer sb_publishable_vXzwxdpfrzmbwtbR5aXcKA_cMUO8hVB''
    ),
    body := ''{}''::jsonb
  );
  ', true),
      ('gh-aqar-sweep', '5 */8 * * *', 'select public.trigger_gh_workflow(''aqar-sweep.yml'')', true),
      ('gh-aqar-commercial', '15 */8 * * *', 'select public.trigger_gh_workflow(''aqar-commercial-sweep.yml'')', true),
      ('gh-wasalt-res', '40 */8 * * *', 'select public.trigger_gh_workflow(''wasalt-residential-sweep.yml'')', true),
      ('gh-wasalt-com', '45 */8 * * *', 'select public.trigger_gh_workflow(''wasalt-commercial-sweep.yml'')', true),
      ('gh-aqar-liveness', '0 1 * * *', 'select public.trigger_gh_workflow(''aqar-liveness.yml'')', true),
      ('gh-wasalt-enrich', '0 5 * * *', 'select public.trigger_gh_workflow(''wasalt-enrich.yml'')', true),
      ('gh-aqar-cleanup', '0 2 * * 0', 'select public.trigger_gh_workflow(''aqar-cleanup.yml'')', true),
      ('gh-wasalt-cleanup', '30 2 * * 0', 'select public.trigger_gh_workflow(''wasalt-cleanup.yml'')', true),
      ('gh-small-sources', '22 4 * * *', 'select public.trigger_gh_workflow(''small-sources-sync.yml'')', true),
      ('stale-listings-mark', '0 4 * * *', 'select public.mark_stale_listings_inactive(7)', true),
      ('gh-muktamel-weekly', '0 3 * * 1', 'select public.trigger_gh_workflow(''muktamel-sync.yml'')', false),
      ('gh-gathern-daily', '40 4 * * *', 'select public.trigger_gh_workflow(''gathern-sync.yml'')', true),
      ('refresh-location-index', '30 7 * * *', 'set statement_timeout to ''1200s''; refresh materialized view concurrently public.listing_location_index; refresh materialized view concurrently public.listing_location_canonical_mv; analyze public.listing_location_index; analyze public.listing_location_canonical_mv; insert into public.mon_mv_refresh_log(object_name, refreshed_at, rows_after, note) select ''listing_location_index'', now(), count(*), ''jobid16'' from public.listing_location_index on conflict (object_name) do update set refreshed_at = excluded.refreshed_at, rows_after = excluded.rows_after, note = excluded.note; insert into public.mon_mv_refresh_log(object_name, refreshed_at, rows_after, note) select ''listing_location_canonical_mv'', now(), count(*), ''jobid16'' from public.listing_location_canonical_mv on conflict (object_name) do update set refreshed_at = excluded.refreshed_at, rows_after = excluded.rows_after, note = excluded.note;', true),
      ('refresh_listing_native_location_v1', '0 * * * *', 'set statement_timeout to ''900s''; refresh materialized view concurrently public.active_listing_ids_v2; refresh materialized view concurrently public.listing_native_location_v1; analyze public.active_listing_ids_v2; analyze public.listing_native_location_v1; insert into public.mon_mv_refresh_log(object_name, refreshed_at, rows_after, note) select ''active_listing_ids_v2'', now(), count(*), ''jobid17'' from public.active_listing_ids_v2 on conflict (object_name) do update set refreshed_at = excluded.refreshed_at, rows_after = excluded.rows_after, note = excluded.note; insert into public.mon_mv_refresh_log(object_name, refreshed_at, rows_after, note) select ''listing_native_location_v1'', now(), count(*), ''jobid17'' from public.listing_native_location_v1 on conflict (object_name) do update set refreshed_at = excluded.refreshed_at, rows_after = excluded.rows_after, note = excluded.note;', true),
      ('refresh-loc-rel-signals', '4-59/15 * * * *', 'CALL public.loc_rel_refresh_tick();', true),
      ('gh-aqarmonthly-daily', '0 6 * * *', 'select public.trigger_gh_workflow(''aqarmonthly-sync.yml'')', true),
      ('crawl-stats-hourly', '50 * * * *', 'select public.capture_crawl_stats()', true),
      ('resolve-aqar-locations', '1-59/10 * * * *', 'select resolve_aqar_locations();', true),
      ('sync-search-listings-ar', '14 * * * *', 'set statement_timeout to ''600s''; select * from public.sync_search_listings_ar(); select public.refresh_rnpl_flags(); select public.sync_payment_monthly(); select * from public.sync_all_rich_attrs();', true),
      ('location-selftest-hourly', '45 * * * *', 'set statement_timeout to ''300s''; select public.run_location_selftest();', true),
      ('auto-recover-false-inactive', '20 5 * * *', 'select public.auto_recover_false_inactive();', true),
      ('novel-type-alarm', '27 * * * *', 'select public.detect_novel_property_types();', true),
      ('location-pipeline-monitor', '17 * * * *', 'select public.location_pipeline_monitor();', true),
      ('resolve-english-city-overlay', '6 * * * *', 'select public.resolve_english_city_overlay();', true),
      ('dealapp-coverage-snapshot', '7 6 * * *', 'select public.ops_snapshot_dealapp_coverage();', true),
      ('dealapp-location-propagate', '8-59/10 * * * *', 'SET statement_timeout = ''90s''; SELECT public.propagate_dealapp_resolved_locations();', true),
      ('mon-aqar-ppm-as-total', '25 * * * *', 'select public.mon_detect_aqar_ppm_as_total();', true),
      ('mon-pii-capture-sweep', '36 * * * *', 'select mon_scan_pii_capture_batch(15000);', true),
      ('safety_barrier_state', '23 3 * * *', 'select public.refresh_safety_barrier_state();', true)
    ) as t(jobname, schedule, command, active)
  loop
    select j.schedule, j.command, j.active into v_sched, v_cmd, v_active
      from cron.job j where j.jobname = r.jobname;
    if not found then
      perform cron.schedule(r.jobname, r.schedule, r.command);
      if not r.active then
        perform cron.alter_job(
          (select jobid from cron.job where jobname = r.jobname), active => false);
      end if;
      created := created + 1;
    elsif v_sched <> r.schedule or v_cmd <> r.command or v_active <> r.active then
      raise exception 'cron job "%" differs from this mirror (live schedule=%, active=%) — update the mirror to match live; never blind-overwrite a live job', r.jobname, v_sched, v_active;
    end if;
  end loop;
  raise notice 'cron mirror: % job(s) re-created; the rest verified byte-identical to live', created;
end $mig$;

-- All 30 must exist after the block, and the paused one must still be paused.
do $$
declare n int; muk boolean;
begin
  select count(*) into n from cron.job where jobname in
    ('refresh-listings','gh-aqar-sweep','gh-aqar-commercial','gh-wasalt-res','gh-wasalt-com',
     'gh-aqar-liveness','gh-wasalt-enrich','gh-aqar-cleanup','gh-wasalt-cleanup','gh-small-sources',
     'stale-listings-mark','gh-muktamel-weekly','gh-gathern-daily','refresh-location-index',
     'refresh_listing_native_location_v1','refresh-loc-rel-signals','gh-aqarmonthly-daily',
     'crawl-stats-hourly','resolve-aqar-locations','sync-search-listings-ar','location-selftest-hourly',
     'auto-recover-false-inactive','novel-type-alarm','location-pipeline-monitor',
     'resolve-english-city-overlay','dealapp-coverage-snapshot','dealapp-location-propagate',
     'mon-aqar-ppm-as-total','mon-pii-capture-sweep','safety_barrier_state');
  if n <> 30 then raise exception 'cron mirror: expected 30 jobs, found %', n; end if;
  select active into strict muk from cron.job where jobname = 'gh-muktamel-weekly';
  if muk then raise exception 'gh-muktamel-weekly must remain paused (active=false)'; end if;
end $$;
