-- Rotating «Filter search → chat bubble» opening greeting (owner rule 2026-09-18).
--
-- The Filter-search-submission bubble in the chat (src/data/search.ts filterToChat(), rendered via
-- the i18n key "I'm looking for {what}{detail} {verb} in {place}{price}") used to always open with
-- the same hardcoded "ارحب إزهله 👋، " prefix, followed by the filter summary ("أبحث عن ..."). The
-- owner asked for ONLY that opening to rotate through a curated list, so consecutive searches don't
-- read as robotic repetition — everything after the opening is UNCHANGED (owner explicit: do not
-- touch the filter-generated sentence itself, do not touch the separate AI-chat greeting in
-- agent.tsx's greetingText(), do not touch the Advanced-Filter/interview bubble in interview.tsx).
--
-- Table holds BOTH languages: ar rows power the rotation today; en rows are stored for when English
-- ships (the product is Arabic-only today — see agent.tsx's greetingText() comment) so this data
-- survives without re-typing it later. 100 rows per language, owner-authored 2026-09-18.
create table public.ui_filter_greetings (
  id bigint generated always as identity primary key,
  lang text not null check (lang in ('ar','en')),
  sort_order int not null,
  greeting text not null,
  emoji text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (lang, sort_order)
);

comment on table public.ui_filter_greetings is
  'Rotation pool for the opening of the Filter-search-submission chat bubble ("{greeting}، إزهله {emoji}"). ar rows are live; en rows stored for future English support. Owner rule 2026-09-18.';

alter table public.ui_filter_greetings enable row level security;
-- No policy is added: RLS stays default-deny for direct table access. The client reads ONLY through
-- the security-definer RPC below (same shape as loader_active_platforms_ar), so the table is never
-- exposed via a future generic PostgREST route by accident.

-- Mirrors loader_active_platforms_ar()'s shape exactly (supabase/migrations/20260830013418_...):
-- cheap, anon-readable, security definer, explicit search_path.
create or replace function public.ui_filter_greetings_ar()
returns table(greeting text, emoji text)
language sql
stable
security definer
set search_path = public
as $$
  select greeting, emoji
  from public.ui_filter_greetings
  where lang = 'ar' and active
  order by sort_order;
$$;

comment on function public.ui_filter_greetings_ar() is
  'Active Arabic greeting-rotation rows for the Filter-search chat bubble opening. See src/data/loaderFilterGreetings.ts. Owner rule 2026-09-18.';

revoke all on function public.ui_filter_greetings_ar() from public;
grant execute on function public.ui_filter_greetings_ar() to anon, authenticated;

insert into public.ui_filter_greetings (lang, sort_order, greeting, emoji) values
  ('ar', 1, 'هلا', '👋'),
  ('ar', 2, 'يا هلا', '🙌'),
  ('ar', 3, 'هلا والله', '💚'),
  ('ar', 4, 'مرحبا', '😊'),
  ('ar', 5, 'أرحب', '✨'),
  ('ar', 6, 'يا مرحبا', '🤝'),
  ('ar', 7, 'حياك', '😎'),
  ('ar', 8, 'أهلين', '🌟'),
  ('ar', 9, 'هلا وغلا', '🤍'),
  ('ar', 10, 'يا هلا والله', '🔥'),
  ('ar', 11, 'مرحبتين', '😄'),
  ('ar', 12, 'أرحب والله', '🫡'),
  ('ar', 13, 'حيا الله', '🙏'),
  ('ar', 14, 'يا حي', '🌴'),
  ('ar', 15, 'هلا هلا', '🎉'),
  ('ar', 16, 'يا مرحبا والله', '💫'),
  ('ar', 17, 'أهلًا', '🌿'),
  ('ar', 18, 'أهلين وسهلين', '😁'),
  ('ar', 19, 'يا هلا وغلا', '🏡'),
  ('ar', 20, 'حياك الله', '☀️'),
  ('ar', 21, 'أرحب مليون', '🚀'),
  ('ar', 22, 'هلا بالزين', '😉'),
  ('ar', 23, 'يا مرحبتين', '🌹'),
  ('ar', 24, 'يالله حيه', '⚡'),
  ('ar', 25, 'يا هلا فيك', '🥳'),
  ('ar', 26, 'مرحبا الساع', '🌤️'),
  ('ar', 27, 'هلا بك', '🏠'),
  ('ar', 28, 'يا حيّك', '😌'),
  ('ar', 29, 'أرحب وأهلين', '💯'),
  ('ar', 30, 'يا مرحبا مليون', '🌧️'),
  ('ar', 31, 'هلا بالطلة', '🌞'),
  ('ar', 32, 'حيا الله هالطلة', '🍃'),
  ('ar', 33, 'يا حي هالصوت', '🎙️'),
  ('ar', 34, 'أهلًا وسهلًا', '🔎'),
  ('ar', 35, 'أرحب وأسهِل', '😃'),
  ('ar', 36, 'هلا من جديد', '🔄'),
  ('ar', 37, 'يا مرحبا تراحيب', '🌸'),
  ('ar', 38, 'حياك ربي', '👌'),
  ('ar', 39, 'هلا فيك', '🧭'),
  ('ar', 40, 'يا هلا بك', '💪'),
  ('ar', 41, 'حي الله من جانا', '🏘️'),
  ('ar', 42, 'أهلين والله', '😋'),
  ('ar', 43, 'يا حي من لفانا', '🛬'),
  ('ar', 44, 'مرحبا مليون', '💎'),
  ('ar', 45, 'أرحب يا', '😄'),
  ('ar', 46, 'هلا والله ومرحبا', '🎈'),
  ('ar', 47, 'حي الله', '😊'),
  ('ar', 48, 'يا مرحبا بك', '🧡'),
  ('ar', 49, 'أهلين فيك', '🪄'),
  ('ar', 50, 'يامرحبا', '🥰'),
  ('ar', 51, 'حياك يا', '🌵'),
  ('ar', 52, 'أرحب تراحيب', '🌊'),
  ('ar', 53, 'يا هلا بالطلة', '📍'),
  ('ar', 54, 'حيّاك الله', '🏙️'),
  ('ar', 55, 'هلا ومرحبا', '🛋️'),
  ('ar', 56, 'يا مرحبا بالزين', '🌺'),
  ('ar', 57, 'حياك وين ما كنت', '🗺️'),
  ('ar', 58, 'أهلًا ومرحبًا', '🎯'),
  ('ar', 59, 'يا حي الله', '🍀'),
  ('ar', 60, 'أهلًا أهلًا', '🙋'),
  ('ar', 61, 'مرحبا من القلب', '❤️'),
  ('ar', 62, 'حياك وأكثر', '💐'),
  ('ar', 63, 'يا هلا مليون', '⭐'),
  ('ar', 64, 'أرحب من جديد', '🌅'),
  ('ar', 65, 'هلا يا', '😎'),
  ('ar', 66, 'حيّاك ربي', '🏆'),
  ('ar', 67, 'يا مرحبا فيك', '🔑'),
  ('ar', 68, 'أهلين بالطلة', '🥂'),
  ('ar', 69, 'يالله حيّك', '🎊'),
  ('ar', 70, 'هلا ومرحبتين', '🧩'),
  ('ar', 71, 'يا هلا يا هلا', '🎵'),
  ('ar', 72, 'حيا الله هالحضور', '🎭'),
  ('ar', 73, 'مرحبا فيك', '🏗️'),
  ('ar', 74, 'أرحب وهلا', '🔔'),
  ('ar', 75, 'يا حي هالطلة', '🌙'),
  ('ar', 76, 'هلا من القلب', '💌'),
  ('ar', 77, 'مرحبتين كبار', '🪁'),
  ('ar', 78, 'حياك بكل وقت', '⏰'),
  ('ar', 79, 'يا هلا ومرحبتين', '🏖️'),
  ('ar', 80, 'أهلين يا', '🌻'),
  ('ar', 81, 'حي الله من حضر', '🎪'),
  ('ar', 82, 'هلا يا صاحبتنا', '😄'),
  ('ar', 83, 'أرحب وألف هلا', '🏅'),
  ('ar', 84, 'يا مرحبا يا', '🍀'),
  ('ar', 85, 'حياك يا كفو', '💪'),
  ('ar', 86, 'هلا بك والله', '🛎️'),
  ('ar', 87, 'يا هلا بهالطلة', '🎇'),
  ('ar', 88, 'أهلين ومرحبا', '🥇'),
  ('ar', 89, 'حياك ومرحبا', '🛟'),
  ('ar', 90, 'أرحب يا كفو', '🦅'),
  ('ar', 91, 'هلا يا زين', '🌙'),
  ('ar', 92, 'يا حي من وصل', '🚪'),
  ('ar', 93, 'مرحبا وألف مرحبا', '🎁'),
  ('ar', 94, 'حياك يا', '🐺'),
  ('ar', 95, 'هلا فيك والله', '🧿'),
  ('ar', 96, 'يا مرحبا', '💡'),
  ('ar', 97, 'أهلًا بالطلة', '🎨'),
  ('ar', 98, 'حياك الله', '🌍'),
  ('ar', 99, 'أرحب تراحيب', '👑'),
  ('ar', 100, 'يا هلا والله يا', '🏹'),
  ('en', 1, 'Hi', '👋'),
  ('en', 2, 'Hey', '🙌'),
  ('en', 3, 'Hello', '💚'),
  ('en', 4, 'Hey there', '😊'),
  ('en', 5, 'Hi there', '✨'),
  ('en', 6, 'Hello there', '🤝'),
  ('en', 7, 'Heyyy', '😎'),
  ('en', 8, 'Hi', '🌟'),
  ('en', 9, 'Hey', '🤍'),
  ('en', 10, 'Hello', '🔥'),
  ('en', 11, 'Hey there', '😄'),
  ('en', 12, 'Hi again', '🫡'),
  ('en', 13, 'Hello again', '🙏'),
  ('en', 14, 'Hey hey', '🌴'),
  ('en', 15, 'Hi hi', '🎉'),
  ('en', 16, 'Hey', '💫'),
  ('en', 17, 'Hello', '🌿'),
  ('en', 18, 'Hey there', '😁'),
  ('en', 19, 'Hiya', '🏡'),
  ('en', 20, 'Hello there', '☀️'),
  ('en', 21, 'Heyyy', '🚀'),
  ('en', 22, 'What''s up', '😉'),
  ('en', 23, 'Hi there', '🌹'),
  ('en', 24, 'Hey', '⚡'),
  ('en', 25, 'Hello', '🥳'),
  ('en', 26, 'Hey there', '🌤️'),
  ('en', 27, 'Hi', '🏠'),
  ('en', 28, 'Heyyy', '😌'),
  ('en', 29, 'Hello hello', '💯'),
  ('en', 30, 'Hey there', '🌧️'),
  ('en', 31, 'Hi', '🌞'),
  ('en', 32, 'Hello', '🍃'),
  ('en', 33, 'Hey', '🎙️'),
  ('en', 34, 'Hi there', '🔎'),
  ('en', 35, 'Hey hey', '😃'),
  ('en', 36, 'Hello again', '🔄'),
  ('en', 37, 'Hey there', '🌸'),
  ('en', 38, 'Hi', '👌'),
  ('en', 39, 'What''s good', '🧭'),
  ('en', 40, 'Hey', '💪'),
  ('en', 41, 'Hello there', '🏘️'),
  ('en', 42, 'Hiya', '😋'),
  ('en', 43, 'Heyyy', '🛬'),
  ('en', 44, 'Hello', '💎'),
  ('en', 45, 'Hey', '😄'),
  ('en', 46, 'Hi there', '🎈'),
  ('en', 47, 'Hello hello', '😊'),
  ('en', 48, 'Hey there', '🧡'),
  ('en', 49, 'Hi', '🪄'),
  ('en', 50, 'Heyyy', '🥰'),
  ('en', 51, 'Hello there', '🌵'),
  ('en', 52, 'Hey', '🌊'),
  ('en', 53, 'Hi there', '📍'),
  ('en', 54, 'Hello', '🏙️'),
  ('en', 55, 'Hey there', '🛋️'),
  ('en', 56, 'Hi', '🌺'),
  ('en', 57, 'Hello there', '🗺️'),
  ('en', 58, 'Hey hey', '🎯'),
  ('en', 59, 'Hiya', '🍀'),
  ('en', 60, 'Hello hello', '🙋'),
  ('en', 61, 'Hey from me', '❤️'),
  ('en', 62, 'Hi there', '💐'),
  ('en', 63, 'Heyyy', '⭐'),
  ('en', 64, 'Hello again', '🌅'),
  ('en', 65, 'What''s up', '😎'),
  ('en', 66, 'Hey there', '🏆'),
  ('en', 67, 'Hi', '🔑'),
  ('en', 68, 'Hello', '🥂'),
  ('en', 69, 'Hey hey', '🎊'),
  ('en', 70, 'Hi there', '🧩'),
  ('en', 71, 'Heyyy', '🎵'),
  ('en', 72, 'Hello there', '🎭'),
  ('en', 73, 'Hi', '🏗️'),
  ('en', 74, 'Hey', '🔔'),
  ('en', 75, 'Hello', '🌙'),
  ('en', 76, 'Hi there', '💌'),
  ('en', 77, 'Hey there', '🪁'),
  ('en', 78, 'Hello again', '⏰'),
  ('en', 79, 'Hiya', '🏖️'),
  ('en', 80, 'Hey', '🌻'),
  ('en', 81, 'Hello there', '🎪'),
  ('en', 82, 'Hi', '😄'),
  ('en', 83, 'Heyyy', '🏅'),
  ('en', 84, 'Hello', '🍀'),
  ('en', 85, 'What''s up', '💪'),
  ('en', 86, 'Hey there', '🛎️'),
  ('en', 87, 'Hi', '🎇'),
  ('en', 88, 'Hello hello', '🥇'),
  ('en', 89, 'Hey', '🛟'),
  ('en', 90, 'Hi there', '🦅'),
  ('en', 91, 'Hello', '🌙'),
  ('en', 92, 'Heyyy', '🚪'),
  ('en', 93, 'Hi there', '🎁'),
  ('en', 94, 'Hey', '🐺'),
  ('en', 95, 'Hello there', '🧿'),
  ('en', 96, 'Hi', '💡'),
  ('en', 97, 'Hey there', '🎨'),
  ('en', 98, 'Hello', '🌍'),
  ('en', 99, 'Heyyy', '👑'),
  ('en', 100, 'Hi', '🏹');
