-- CORRECTION of 20260831113443, same run (routine #5, 2026-08-31). Read this before that file.
--
-- WHAT I GOT WRONG. 20260831113443 concluded that listing_age_resolved's table list was a
-- hand-maintained UNION ALL that had "forgotten" four platforms, and appended four blocks to it
-- directly. Both halves of that were wrong:
--
--   1. listing_age_resolved is NOT hand-maintained. It is GENERATED by rebuild_age_producer()
--      from the age_source_registry table. Editing the view directly is the same antipattern
--      AGENTS.md forbids for the four AF eligibility RPCs ("never hand-edit -- go through the
--      shared clause + rebuild"). The next rebuild_age_producer() call overwrote the edit within
--      minutes, exactly as it should have. Production was never left in the hand-edited state.
--
--   2. The four platforms are not "forgotten" -- they are DELIBERATELY WITHHELD. Two of them
--      (aldarim_commercial, mizlaj_commercial) are registered with trusted = true but score
--      verdict = 'too_small' from age_source_health() (n_aged = 2), and rebuild_age_producer()
--      admits canonical_column sources only at verdict = 'ok'. A platform with one or two aged
--      rows is not yet a trustworthy age source, and withholding it is the designed behaviour.
--      "Weird does not mean wrong": the gate was right and the audit was wrong.
--
-- The 7 index rows that the hand-edited view briefly fed into search_listings_ar are restored to
-- NULL by the next sync_search_listings_ar(), because the sync's own change-detection compares
-- s3.property_age against v.property_age. That is run explicitly at the end of this migration
-- rather than left to cron, since this run caused the divergence.
--
-- WHAT SURVIVES, corrected. There IS a real gap, but it is narrower than claimed: two served
-- platforms publish plausible ages and appear in age_source_registry NOT AT ALL --
-- eastabha_residential_listings and erapulse_commercial_listings. Nobody has ever adjudicated
-- them, so their age is withheld by silence rather than by decision. That is worth an alert;
-- a health-gated or explicitly untrusted exclusion is NOT, and the detector shipped in
-- 20260831113443 could not tell the two apart -- it keyed on "absent from the view", so it would
-- have raised a permanent false P2 against the very gate that was working correctly.
--
-- A barrier that manufactures a false alarm is worse than no barrier, so it is redefined here to
-- key on absence from the REGISTRY (undecided) rather than absence from the VIEW (which conflates
-- undecided with decided-no).

begin;

create or replace function public.mon_detect_age_resolver_platform_gap()
returns integer
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  n int := 0; v_total bigint := 0; v_rows jsonb := '[]'::jsonb; v_open text;
  r record; c bigint;
begin
  -- A platform is a GAP only when nothing has ever decided about it. Registered-but-withheld
  -- (trusted = false, or age_source_health() verdict <> 'ok') is a decision, and stays silent:
  -- that is rebuild_age_producer() doing its job, not a defect.
  for r in
    select c.table_name as st
      from information_schema.columns c
     where c.table_schema = 'public'
       and c.column_name = 'property_age'
       and c.table_name in (select distinct source_table from public.search_listings_ar)
       and not exists (select 1 from public.age_source_registry g where g.source_table = c.table_name)
  loop
    execute format('select count(*) from public.%I where active and property_age >= 0 and property_age <= 100', r.st)
      into c;
    if c > 0 then
      v_total := v_total + c;
      v_rows := v_rows || jsonb_build_array(jsonb_build_object('source_table', r.st, 'published_ages', c));
    end if;
  end loop;

  select severity into v_open from public.alert_event
   where dedup_key = 'age_resolver_platform_gap' and resolved_at is null
   order by created_at desc limit 1;

  if v_total = 0 then
    if v_open is not null then
      perform public.mon_resolve_key('age_resolver_platform_gap', 'age_resolver_platform_gap');
    end if;
    return 0;
  end if;

  n := public.mon_raise('P2', 'age_resolver_platform_gap', 'all', 'age_resolver_platform_gap',
    jsonb_build_object(
      'undecided_rows', v_total,
      'tables', v_rows,
      'why', 'These source tables are SERVED in search_listings_ar and publish a plausible '
          || 'property_age (active, 0..100) in their own raw column, but they appear in '
          || 'age_source_registry NOT AT ALL. Their age is therefore withheld from Advanced Filter '
          || 'by SILENCE rather than by decision -- nobody has ever judged whether the platform''s '
          || 'age field means what we think it means. Contrast: a registry row with trusted = false, '
          || 'or one whose age_source_health() verdict is not ''ok'' (e.g. too_small), is a '
          || 'DELIBERATE withholding by rebuild_age_producer() and is correctly silent here.',
      'adjudicate', 'Do NOT hand-edit listing_age_resolved -- it is generated by '
          || 'rebuild_age_producer() and any direct edit is overwritten by the next rebuild. '
          || 'Adjudicate the platform against its LIVE source (per AGENTS.md permanent rule #2, a '
          || 'missing captured field is not evidence the source omits it), then insert an '
          || 'age_source_registry row with the right strategy/trusted flag and run '
          || 'rebuild_age_producer(). The health gate then decides admission on its own.'));
  return n;
end
$fn$;

-- Re-assert the canonical view from its generator, so the state is the generator's and not a
-- leftover of the reverted hand-edit, whatever order things ran in.
do $$
declare msg text; tabs int;
begin
  select public.rebuild_age_producer() into msg;
  select count(distinct source_table) into tabs from public.listing_age_resolved;
  raise notice 'rebuild_age_producer: % (view now covers % source tables)', msg, tabs;
  if position('eastabha_residential_listings' in pg_get_viewdef('public.listing_age_resolved'::regclass, true)) > 0 then
    raise exception 'the hand-edited block is still present after rebuild -- investigate before proceeding';
  end if;
end $$;

commit;
