-- SERVICE FACILITIES («مرافق خدمية») JOIN THE TAXONOMY + district-picklist filter learns Arabic digits.
--
-- OWNER DECISION (2026-09-11, ops_incident #172): map the defensible source-published facility types
-- (مستشفى، مركز أعمال، منتجع، موقع صراف) under the existing مرافق خدمية box; keep genuinely-unknown
-- values («بلك» — its own title says أرض; eastabha "unknown"; october "Other") explicitly unknown.
--
-- ROOT CAUSE the taxonomy half fixes: enforce_price_size_sanity (BEFORE trigger on search_listings_ar)
-- replaces any type_ar absent from known_type_ar with the «غير معروف» sentinel, so every hourly sync
-- wrote the native type and the trigger re-sentineled it — the rows were counted in the index but
-- selectable by no نوع cohort. Seeds below are the verify-taxonomy --emit-sql output regenerated from
-- src/data/taxonomy.source.json in the same PR (gate: ZERO drift across JSON/TS/normalize.py/seeds).
--
-- SECOND FIX (numbers-trust audit, same session): district_ar_looks_bogus was ASCII-digit-blind and
-- description-leak-blind — 'النسيم مساحه ٦٠٠' (Arabic-Indic 3-digit plot size) and 7 عرعر
-- listing-description fragments (': الجوهره', '...مكونه من :', a 💎 emoji row) sat in
-- loc_canonical_district as selectable "districts". Rules extended; refresh purges them. Genuine
-- numbered districts (حي المصيف 1/2/3, المحمدية 3, زهراء ١ — single digits) are untouched.
--
-- Plus one doc fix: mon_refresh_targets note for the sync pass said jobid 28 runs at :14; live is :36.

-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/propertyTypes.ts (CLEAN_TO_TYPE_AR + CLEAN_MACRO). Regenerate
-- after any change to the clean-type map, then re-apply so detect_novel_property_types() (pg_cron
-- jobid 33) and the trust checks stay in sync with what the app can actually reach.
-- macro = which category owns the label: Residential | Commercial | both («عمارة» only — resolved by
-- source-table kind at read time). 55 covered type_ar labels.
create table if not exists public.known_type_ar (type_ar text primary key, macro text);
alter table public.known_type_ar add column if not exists macro text;  -- upgrade path from 1-col shape
-- Full re-sync: the generated set is authoritative.
truncate public.known_type_ar;
insert into public.known_type_ar (type_ar, macro) values
  ('أرض', 'Residential'),
  ('أرض تجارية', 'Commercial'),
  ('أرض زراعية', 'Residential'),
  ('أرض سكنية', 'Residential'),
  ('أرض صناعية', 'Commercial'),
  ('إستراحة', 'Residential'),
  ('استراحة', 'Residential'),
  ('استوديو', 'Residential'),
  ('برج', 'Residential'),
  ('برج اتصالات', 'Commercial'),
  ('بنك', 'Commercial'),
  ('بيت', 'Residential'),
  ('تاون هاوس', 'Residential'),
  ('حوش', 'Residential'),
  ('درايف ثرو', 'Commercial'),
  ('دوبلكس', 'Residential'),
  ('دور', 'Residential'),
  ('ستوديو', 'Residential'),
  ('سكن عمال', 'Commercial'),
  ('سينما', 'Commercial'),
  ('شاليه', 'Residential'),
  ('شقة', 'Residential'),
  ('شقَّة صغيرة (استوديو)', 'Residential'),
  ('صالة', 'Commercial'),
  ('عمارة', 'both'),
  ('غرفة', 'Residential'),
  ('غير معروف', 'both'),
  ('فندق', 'Commercial'),
  ('فيلا', 'Residential'),
  ('كشك', 'Commercial'),
  ('مبنى تجاري', 'Commercial'),
  ('مبنى شقق مخدومة', 'Residential'),
  ('مجمع', 'Residential'),
  ('مجمع سكني', 'Residential'),
  ('محطة', 'Commercial'),
  ('محطة بنزين', 'Commercial'),
  ('محطة وقود', 'Commercial'),
  ('محل', 'Commercial'),
  ('مخازن سحابية', 'Commercial'),
  ('مخيم', 'Residential'),
  ('مدرسة', 'Commercial'),
  ('مركز أعمال', 'Commercial'),
  ('مركز صحي', 'Commercial'),
  ('مزرعة', 'Residential'),
  ('مستشفى', 'Commercial'),
  ('مستودع', 'Commercial'),
  ('مصنع', 'Commercial'),
  ('معرض', 'Commercial'),
  ('مكاتب مشتركة', 'Commercial'),
  ('مكتب', 'Commercial'),
  ('ملحق علوي', 'Residential'),
  ('منتجع', 'Commercial'),
  ('مواقف', 'Commercial'),
  ('موقع صراف', 'Commercial'),
  ('ورشة', 'Commercial');
notify pgrst, 'reload schema';

-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/taxonomy.source.json (labels: EN token -> canonical Arabic
-- label; identical to propertyTypes.ts EN_TO_AR). Regenerate with `npm run verify:emit-sql`, then
-- re-apply so the Arabic display label the app resolves for each English type stays in sync with the DB.
-- Full re-sync: the generated set is authoritative. 44 canonical EN->AR type labels.
create table if not exists public.type_label_ar (en text primary key, ar text not null);
truncate public.type_label_ar;
insert into public.type_label_ar (en, ar) values
  ('ATM Site', 'موقع صراف'),
  ('Agriculture Plot', 'أرض زراعية'),
  ('Apartment', 'شقة'),
  ('Bank', 'بنك'),
  ('Building', 'عمارة'),
  ('Business Center', 'مركز أعمال'),
  ('Camp', 'مخيم'),
  ('Chalet', 'شاليه'),
  ('Cinema', 'سينما'),
  ('Commercial Building', 'مبنى تجاري'),
  ('Commercial Land', 'أرض تجارية'),
  ('Compound', 'مجمع'),
  ('Duplex', 'دوبلكس'),
  ('Factory', 'مصنع'),
  ('Farm', 'مزرعة'),
  ('Floor', 'دور'),
  ('Gas Station', 'محطة وقود'),
  ('Hall', 'صالة'),
  ('Health Center', 'مركز صحي'),
  ('Hospital', 'مستشفى'),
  ('Hotel', 'فندق'),
  ('House', 'بيت'),
  ('Industrial Land', 'أرض صناعية'),
  ('Kiosk', 'كشك'),
  ('Land', 'أرض'),
  ('Office', 'مكتب'),
  ('Palace', 'فيلا'),
  ('Parking', 'مواقف'),
  ('Residential Building', 'عمارة سكنية'),
  ('Residential Land', 'أرض سكنية'),
  ('Resort', 'منتجع'),
  ('Rest House', 'استراحة'),
  ('Room', 'غرفة'),
  ('School', 'مدرسة'),
  ('Shop', 'محل'),
  ('Showroom', 'معرض'),
  ('Specialized Facilities', 'منشآت متخصصة'),
  ('Staff Housing', 'سكن عمال'),
  ('Station', 'محطة'),
  ('Studio', 'استوديو'),
  ('Telecom Tower', 'برج اتصالات'),
  ('Villa', 'فيلا'),
  ('Warehouse', 'مستودع'),
  ('Workshop', 'ورشة');
notify pgrst, 'reload schema';

-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/taxonomy.source.json (every raw alias in cleanTypes[].query.rawTypes
-- plus the ambiguous «Building» raw; identical to the propertyTypes.ts RAW_TO_CLEAN key set + «Building»).
-- This is the discovery allowlist detect_novel_property_types() (pg_cron jobid 33) diffs live data
-- against; a raw type absent here is flagged as novel. APPEND-ONLY: existing rows' added_at / note are
-- preserved (ON CONFLICT DO NOTHING), so applying this never resets discovery history. 64 known raw aliases.
create table if not exists public.known_property_types (
  raw_type text primary key,
  added_at timestamptz not null default now(),
  note text
);
insert into public.known_property_types (raw_type) values
  ('ATM Site'),
  ('Agriculture Plot'),
  ('Apartment'),
  ('Bank'),
  ('Building'),
  ('Business Center'),
  ('Camp'),
  ('Chalet'),
  ('Cinema'),
  ('Commercial Building'),
  ('Commercial Land'),
  ('Duplex'),
  ('Factory'),
  ('Farm'),
  ('Floor'),
  ('Gas Station'),
  ('Hall'),
  ('Health Center'),
  ('Hospital'),
  ('Hotel'),
  ('House'),
  ('Industrial Land'),
  ('Kiosk'),
  ('Land'),
  ('Office'),
  ('Palace'),
  ('Parking'),
  ('Residential Land'),
  ('Resort'),
  ('Rest House'),
  ('Room'),
  ('School'),
  ('Shop'),
  ('Showroom'),
  ('Station'),
  ('Studio'),
  ('Telecom Tower'),
  ('Villa'),
  ('Warehouse'),
  ('Workshop'),
  ('إستراحة'),
  ('برج'),
  ('برج اتصالات'),
  ('بنك'),
  ('تاون هاوس'),
  ('حوش'),
  ('درايف ثرو'),
  ('ستوديو'),
  ('سكن عمال'),
  ('شقَّة صغيرة (استوديو)'),
  ('مبنى شقق مخدومة'),
  ('مجمع'),
  ('مجمع سكني'),
  ('محطة بنزين'),
  ('مخازن سحابية'),
  ('مدرسة'),
  ('مركز أعمال'),
  ('مركز صحي'),
  ('مستشفى'),
  ('مكاتب مشتركة'),
  ('ملحق علوي'),
  ('منتجع'),
  ('مواقف'),
  ('موقع صراف')
on conflict (raw_type) do nothing;
notify pgrst, 'reload schema';

-- ── Heal the six dealapp rows the trigger had sentineled (type recomputed from the raw table, never
-- a literal — بلك deliberately stays sentinel per the owner's "keep unknown over inventing"). ──────
update public.search_listings_ar s
set type_ar = canon_type_ar(normalize(d.property_type, NFC))
from public.dealapp_residential_listings d
where s.source_table = 'dealapp_residential_listings'
  and s.listing_id = d.id
  and s.type_ar = 'غير معروف'
  and d.property_type in ('مستشفى', 'مركز أعمال', 'منتجع', 'موقع صراف');

-- ── district_ar_looks_bogus v2: Arabic-Indic digit parity + description-leak vocabulary. ──────────
-- Byte-identical to the live v1 (pulled via pg_get_functiondef immediately before this migration)
-- except: rule 2 counts ٠-٩ runs too; rule 3's strip-set gains ٠-٩ and ':'; new rule 4b rejects
-- description-leak vocabulary («مكون/مكونه من», a colon, or a digit glued directly before letters).
CREATE OR REPLACE FUNCTION public.district_ar_looks_bogus(t text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $function$
  select
    -- 1. explicit subdivision-plan vocabulary ("مخطط" / "مخطط رقم") — always an internal plan
    --    reference ("مخطط الرياض (474/19)", "مخطط رقم 133"), never a neighborhood's own name.
    t ~ 'مخطط'
    -- 2. a run of 3+ consecutive digits anywhere — ASCII or Arabic-Indic (v2: 'النسيم مساحه ٦٠٠'
    --    slipped through the ASCII-only rule). Every genuine numbered Saudi sub-district observed
    --    stays single-digit (حي المصيف 1/2/3, الناصرية 4/5/6, زهراء ١); every 3+ digit run
    --    observed is a plot/scheme/parcel code (776/4, 8511, 602001011, 133, 253/4, ٦٠٠-size leaks).
    or t ~ '[0-9٠-٩]{3,}'
    -- 3. fewer than 2 Arabic letters survive once every digit/space/paren/dash/dot/slash/colon is
    --    stripped — too thin to be a place name at all ("33ج" -> "ج", "8511" -> "").
    or length(regexp_replace(t, '[0-9٠-٩\s\(\)\-\./:]', '', 'g')) < 2
    -- 4. longer than any real Saudi district name gets — catches a leaked full listing
    --    description sitting in the district field by scraper error, not a place at all.
    or length(t) > 40
    -- 4b. description-leak shapes (v2, عرعر cluster 2026-09-11): a colon anywhere, the phrase
    --     «مكون/مكونه/مكونة من» ("consisting of" — listing-description vocabulary, never a place),
    --     or a digit glued directly BEFORE Arabic letters ('1النرجس', a bidi/scraper artifact —
    --     genuine numbered districts put the digit AFTER the name, space-separated).
    or t ~ ':'
    or t ~ 'مكون[هة]? من'
    or t ~ '^[0-9٠-٩]+[ء-ي]'
    -- 5. known non-place values, same mechanism as the existing غير محدد/اخرى/أخرى blocklist.
    or t in ('حكومي1', 'حكومي', 'هخطط 10.5')
$function$;

-- Purge the newly-catchable junk from the picklist now rather than at the next hourly refresh.
-- (Touches ONLY loc_canonical_district's live-promoted fallback; listings are never modified.)
select public.refresh_loc_canonical_district();

-- ── Doc fix: the responder-facing note said jobid 28 runs at :14; cron.job says '36 * * * *'. ─────
update public.mon_refresh_targets
set notes = replace(notes, 'minute 14', 'minute 36')
where object_name = 'search_listings_ar_sync_pass' and notes like '%minute 14%';

-- ── Self-tests ────────────────────────────────────────────────────────────────────────────────────
do $verify$
declare n int; bad text;
begin
  -- the four defensible types are in the allowlist as Commercial
  select count(*) into n from public.known_type_ar
   where type_ar in ('مستشفى','مركز أعمال','منتجع','موقع صراف') and macro = 'Commercial';
  if n <> 4 then raise exception 'service-facility types missing from known_type_ar (found %)', n; end if;

  -- the six dealapp rows now carry their native types and stayed production_ready
  select count(*) into n from public.search_listings_ar
   where source_table = 'dealapp_residential_listings'
     and listing_id in (7059641,7187301,7328583,7438596,8300061,11310478)
     and type_ar in ('مستشفى','مركز أعمال','منتجع','موقع صراف') and production_ready;
  if n <> 6 then raise exception 'expected 6 healed dealapp rows, found %', n; end if;

  -- the trigger no longer sentinels them: an idempotent same-value update must survive
  update public.search_listings_ar set type_ar = type_ar
   where source_table = 'dealapp_residential_listings' and listing_id = 7059641;
  select type_ar into bad from public.search_listings_ar
   where source_table = 'dealapp_residential_listings' and listing_id = 7059641;
  if bad = 'غير معروف' then raise exception 'trigger still sentinels مستشفى after allowlist insert'; end if;

  -- بلك + eastabha "unknown" + october "Other" stay explicitly unknown (source-faithful)
  select count(*) into n from public.search_listings_ar
   where production_ready and type_ar = 'غير معروف';
  if n <> 9 then raise exception 'expected exactly 9 remaining sentinel rows (بلك + 6 eastabha + 2 october), found %', n; end if;

  -- bogus-filter v2 discriminates: junk caught, genuine numbered districts untouched
  if not public.district_ar_looks_bogus('النسيم مساحه ٦٠٠') then raise exception 'v2 missed the Arabic-Indic digit leak'; end if;
  if not public.district_ar_looks_bogus('الجوهره 💎 مكونه من :') then raise exception 'v2 missed the description leak'; end if;
  if not public.district_ar_looks_bogus(': الجوهره') then raise exception 'v2 missed the colon leak'; end if;
  if not public.district_ar_looks_bogus('1النرجس') then raise exception 'v2 missed the glued-digit artifact'; end if;
  if public.district_ar_looks_bogus('حي المصيف 1') then raise exception 'v2 wrongly flags a genuine numbered district'; end if;
  if public.district_ar_looks_bogus('زهراء ١') then raise exception 'v2 wrongly flags a genuine Arabic-Indic single digit'; end if;
  if public.district_ar_looks_bogus('حي النرجس') then raise exception 'v2 wrongly flags a plain district'; end if;

  -- the picklist no longer holds any live-promoted row failing v2
  select count(*) into n from public.loc_canonical_district
   where source = 'live' and public.district_ar_looks_bogus(canonical_district_ar);
  if n <> 0 then raise exception '% live-promoted bogus canonicals survived the refresh', n; end if;
end $verify$;