-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/taxonomy.source.json (every raw alias in cleanTypes[].query.rawTypes
-- plus the ambiguous «Building» raw; identical to the propertyTypes.ts RAW_TO_CLEAN key set + «Building»).
-- This is the discovery allowlist detect_novel_property_types() (pg_cron jobid 33) diffs live data
-- against; a raw type absent here is flagged as novel. APPEND-ONLY: existing rows' added_at / note are
-- preserved (ON CONFLICT DO NOTHING), so applying this never resets discovery history. 53 known raw aliases.
create table if not exists public.known_property_types (
  raw_type text primary key,
  added_at timestamptz not null default now(),
  note text
);
insert into public.known_property_types (raw_type) values
  ('Agriculture Plot'),
  ('Apartment'),
  ('Bank'),
  ('Building'),
  ('Camp'),
  ('Chalet'),
  ('Cinema'),
  ('Commercial Building'),
  ('Commercial Land'),
  ('Duplex'),
  ('Factory'),
  ('Farm'),
  ('Floor'),
  ('Gas Station'),
  ('Hall'),
  ('Health Center'),
  ('Hotel'),
  ('House'),
  ('Industrial Land'),
  ('Kiosk'),
  ('Land'),
  ('Office'),
  ('Palace'),
  ('Parking'),
  ('Residential Land'),
  ('Rest House'),
  ('Room'),
  ('School'),
  ('Shop'),
  ('Showroom'),
  ('Station'),
  ('Studio'),
  ('Telecom Tower'),
  ('Villa'),
  ('Warehouse'),
  ('Workshop'),
  ('برج اتصالات'),
  ('بنك'),
  ('تاون هاوس'),
  ('حوش'),
  ('درايف ثرو'),
  ('ستوديو'),
  ('سكن عمال'),
  ('شقَّة صغيرة (استوديو)'),
  ('مبنى شقق مخدومة'),
  ('مجمع سكني'),
  ('محطة بنزين'),
  ('مخازن سحابية'),
  ('مدرسة'),
  ('مركز صحي'),
  ('مكاتب مشتركة'),
  ('ملحق علوي'),
  ('مواقف')
on conflict (raw_type) do nothing;
notify pgrst, 'reload schema';
