-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/propertyTypes.ts (CLEAN_TO_TYPE_AR + CLEAN_MACRO). Regenerate
-- after any change to the clean-type map, then re-apply so detect_novel_property_types() (pg_cron
-- jobid 33) and the trust checks stay in sync with what the app can actually reach.
-- macro = which category owns the label: Residential | Commercial | both («عمارة» only — resolved by
-- source-table kind at read time). 47 covered type_ar labels.
create table if not exists public.known_type_ar (type_ar text primary key, macro text);
alter table public.known_type_ar add column if not exists macro text;  -- upgrade path from 1-col shape
-- Full re-sync: the generated set is authoritative.
truncate public.known_type_ar;
insert into public.known_type_ar (type_ar, macro) values
  ('أرض', 'Residential'),
  ('أرض تجارية', 'Commercial'),
  ('أرض زراعية', 'Residential'),
  ('أرض سكنية', 'Residential'),
  ('أرض صناعية', 'Commercial'),
  ('استراحة', 'Residential'),
  ('استوديو', 'Residential'),
  ('برج اتصالات', 'Commercial'),
  ('بنك', 'Commercial'),
  ('بيت', 'Residential'),
  ('تاون هاوس', 'Residential'),
  ('حوش', 'Residential'),
  ('درايف ثرو', 'Commercial'),
  ('دوبلكس', 'Residential'),
  ('دور', 'Residential'),
  ('ستوديو', 'Residential'),
  ('سكن عمال', 'Commercial'),
  ('سينما', 'Commercial'),
  ('شاليه', 'Residential'),
  ('شقة', 'Residential'),
  ('شقَّة صغيرة (استوديو)', 'Residential'),
  ('صالة', 'Commercial'),
  ('عمارة', 'both'),
  ('غرفة', 'Residential'),
  ('فندق', 'Commercial'),
  ('فيلا', 'Residential'),
  ('كشك', 'Commercial'),
  ('مبنى تجاري', 'Commercial'),
  ('مبنى شقق مخدومة', 'Residential'),
  ('مجمع سكني', 'Residential'),
  ('محطة', 'Commercial'),
  ('محطة بنزين', 'Commercial'),
  ('محطة وقود', 'Commercial'),
  ('محل', 'Commercial'),
  ('مخازن سحابية', 'Commercial'),
  ('مخيم', 'Residential'),
  ('مدرسة', 'Commercial'),
  ('مركز صحي', 'Commercial'),
  ('مزرعة', 'Residential'),
  ('مستودع', 'Commercial'),
  ('مصنع', 'Commercial'),
  ('معرض', 'Commercial'),
  ('مكاتب مشتركة', 'Commercial'),
  ('مكتب', 'Commercial'),
  ('ملحق علوي', 'Residential'),
  ('مواقف', 'Commercial'),
  ('ورشة', 'Commercial');
notify pgrst, 'reload schema';
