-- GENERATED by ezhalah-app/scripts/verify-taxonomy.ts --emit-sql — DO NOT EDIT BY HAND.
-- Source of truth: ezhalah-app/src/data/taxonomy.source.json (labels: EN token -> canonical Arabic
-- label; identical to propertyTypes.ts EN_TO_AR). Regenerate with `npm run verify:emit-sql`, then
-- re-apply so the Arabic display label the app resolves for each English type stays in sync with the DB.
-- Full re-sync: the generated set is authoritative. 39 canonical EN->AR type labels.
create table if not exists public.type_label_ar (en text primary key, ar text not null);
truncate public.type_label_ar;
insert into public.type_label_ar (en, ar) values
  ('Agriculture Plot', 'أرض زراعية'),
  ('Apartment', 'شقة'),
  ('Bank', 'بنك'),
  ('Building', 'عمارة'),
  ('Camp', 'مخيم'),
  ('Chalet', 'شاليه'),
  ('Cinema', 'سينما'),
  ('Commercial Building', 'مبنى تجاري'),
  ('Commercial Land', 'أرض تجارية'),
  ('Duplex', 'دوبلكس'),
  ('Factory', 'مصنع'),
  ('Farm', 'مزرعة'),
  ('Floor', 'دور'),
  ('Gas Station', 'محطة وقود'),
  ('Hall', 'صالة'),
  ('Health Center', 'مركز صحي'),
  ('Hotel', 'فندق'),
  ('House', 'بيت'),
  ('Industrial Land', 'أرض صناعية'),
  ('Kiosk', 'كشك'),
  ('Land', 'أرض'),
  ('Office', 'مكتب'),
  ('Palace', 'فيلا'),
  ('Parking', 'مواقف'),
  ('Residential Building', 'عمارة سكنية'),
  ('Residential Land', 'أرض سكنية'),
  ('Rest House', 'استراحة'),
  ('Room', 'غرفة'),
  ('School', 'مدرسة'),
  ('Shop', 'محل'),
  ('Showroom', 'معرض'),
  ('Specialized Facilities', 'منشآت متخصصة'),
  ('Staff Housing', 'سكن عمال'),
  ('Station', 'محطة'),
  ('Studio', 'استوديو'),
  ('Telecom Tower', 'برج اتصالات'),
  ('Villa', 'فيلا'),
  ('Warehouse', 'مستودع'),
  ('Workshop', 'ورشة');
notify pgrst, 'reload schema';
